"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");const {test}=require("node:test");const Fastify=require("fastify");
const {openDatabase}=require("../database");const {SessionStore}=require("../session-store");const {StructuredMemoryStore}=require("../structured-memory-store");const {AiMemoryStore}=require("../ai-memory-store");const {ConversationSummaryService}=require("../conversation-summary-service");const {AiTaskRunner}=require("../ai-task-runner");const {registerAiRoutes}=require("../ai-routes");
async function fixture(t,outputs=[]){const dir=await fs.promises.mkdtemp(path.join(os.tmpdir(),"p4b-api-"));const c=openDatabase(path.join(dir,"db.sqlite"));const sessions=new SessionStore({database:c.db,filename:c.filename});const memories=new StructuredMemoryStore({database:c.db});const store=new AiMemoryStore({database:c.db,memoryStore:memories});const adapter={provider:"mock",inputs:[],isConfigured:()=>true,configurationStatus:()=>({provider:"mock",endpointConfigured:true,apiKeyConfigured:true,transportConfigured:true,configured:true}),generate:async input=>{adapter.inputs.push(input);const value=outputs.shift();if(value&&typeof value==="object"&&"content" in value)return value;return{content:value,usage:null,model:input.model,latencyMs:0,toString(){return value}}}};const service=new ConversationSummaryService({database:c.db,store,adapter,summaryModel:"mock-s",extractionModel:"mock-m",provider:"mock"});const config={automationEnabled:false,summaryEnabled:false,extractionEnabled:false,summaryModel:"mock-s",extractionModel:"mock-m",maxAttempts:1,timeoutMs:1000,concurrency:1};const runner=new AiTaskRunner({store,service,config});const app=Fastify({logger:false});registerAiRoutes(app,{store,runner,config,adapter,apiKey:"p4b-token",adminUser:"admin",adminPassword:"admin-secret"});await app.ready();t.after(async()=>{runner.stop();await app.close();c.db.close();await fs.promises.rm(dir,{recursive:true,force:true})});return{app,sessions,store,memories,adapter};}const auth={authorization:"Bearer p4b-token"};

test("summary APIs generate, get and soft-delete with uniform envelope",async t=>{const f=await fixture(t,[JSON.stringify({summary:"API summary",coveredUntilMessageId:1})]);const s=f.sessions.createSession("api");f.sessions.addMessage(s.id,"user","hello");let r=await f.app.inject({method:"POST",url:`/api/v1/chat/sessions/${s.id}/summary/generate`,headers:auth,payload:{force:false}});assert.equal(r.statusCode,200,r.body);assert.equal(r.json().data.summary.summary,"API summary");r=await f.app.inject({method:"GET",url:`/api/v1/chat/sessions/${s.id}/summary`,headers:auth});assert.equal(r.json().data.summary,"API summary");r=await f.app.inject({method:"DELETE",url:`/api/v1/chat/sessions/${s.id}/summary`,headers:auth});assert.equal(r.json().data.status,"deleted");});

test("candidate generation, detail, review lifecycle and list filters",async t=>{const candidate={type:"MOMENT",title:"雨",content:"一起听雨",occurredAt:null,importance:4,confidence:.9,reason:"共同经历"};const f=await fixture(t,[JSON.stringify({candidates:[candidate]})]);const s=f.sessions.createSession("candidate");f.sessions.addMessage(s.id,"user","一起听雨");let r=await f.app.inject({method:"POST",url:`/api/v1/chat/sessions/${s.id}/memory-candidates/generate`,headers:auth,payload:{}});assert.equal(r.statusCode,200,r.body);const id=r.json().data.candidates[0].id;r=await f.app.inject({method:"GET",url:`/api/v1/memory-candidates?status=pending&type=MOMENT&sessionId=${s.id}&keyword=${encodeURIComponent("听雨")}`,headers:auth});assert.equal(r.json().meta.total,1);r=await f.app.inject({method:"POST",url:`/api/v1/memory-candidates/${id}/reject`,headers:auth,payload:{reviewedBy:"tester"}});assert.equal(r.json().data.status,"rejected");r=await f.app.inject({method:"POST",url:`/api/v1/memory-candidates/${id}/reopen`,headers:auth,payload:{}});assert.equal(r.json().data.status,"pending");r=await f.app.inject({method:"POST",url:`/api/v1/memory-candidates/${id}/approve`,headers:auth,payload:{candidate:{title:"人工雨",content:"一起听雨",type:"MOMENT",importance:5,occurredAt:null}}});assert.equal(r.json().data.status,"approved");assert.ok(r.json().data.approvedMemoryId);});

test("job and automation status expose no secrets; auth rejects missing and wrong token",async t=>{const f=await fixture(t);for(const headers of [{},{authorization:"Bearer wrong"}]){const r=await f.app.inject({method:"GET",url:"/api/v1/ai-automation/status",headers});assert.equal(r.statusCode,401);assert.equal(r.json().data,null)}let r=await f.app.inject({method:"GET",url:"/api/v1/ai-automation/status",headers:auth});assert.deepEqual(Object.keys(r.json().data).sort(),["automationEnabled","memoryExtractionAutoEnabled","memoryExtractionModelConfigured","queue","recentErrorCode","summaryAutoEnabled","summaryModelConfigured"].sort());assert.doesNotMatch(r.body,/token|apiKey|baseUrl|prompt|chat/i);r=await f.app.inject({method:"GET",url:"/api/v1/ai-jobs?page=1&limit=10",headers:auth});assert.equal(r.json().meta.total,0);});

test("missing Session and invalid output return controlled errors",async t=>{const f=await fixture(t,["invalid"]);let r=await f.app.inject({method:"GET",url:"/api/v1/chat/sessions/00000000-0000-4000-8000-000000000000/summary",headers:auth});assert.equal(r.statusCode,404);const s=f.sessions.createSession("bad");f.sessions.addMessage(s.id,"user","x");r=await f.app.inject({method:"POST",url:`/api/v1/chat/sessions/${s.id}/summary/generate`,headers:auth,payload:{}});assert.equal(r.statusCode,422);assert.equal(r.json().error.code,"AI_OUTPUT_INVALID");});

test("manual generation API returns products linked to completed jobs while automation stays disabled",async t=>{const f=await fixture(t,[JSON.stringify({summary:"linked",coveredUntilMessageId:1}),JSON.stringify({candidates:[{type:"NOTE",content:"linked candidate"}]})]);const s=f.sessions.createSession("linked");f.sessions.addMessage(s.id,"user","one");let r=await f.app.inject({method:"POST",url:`/api/v1/chat/sessions/${s.id}/summary/generate`,headers:auth,payload:{}});assert.equal(r.statusCode,200,r.body);let body=r.json();assert.equal(body.data.summary.sourceJobId,body.meta.job.id);assert.equal(body.meta.job.status,"completed");r=await f.app.inject({method:"POST",url:`/api/v1/chat/sessions/${s.id}/memory-candidates/generate`,headers:auth,payload:{}});assert.equal(r.statusCode,200,r.body);body=r.json();assert.equal(body.data.candidates[0].sourceJobId,body.meta.job.id);assert.equal(body.meta.job.status,"completed");r=await f.app.inject({method:"GET",url:"/api/v1/ai-automation/status",headers:auth});assert.equal(r.json().data.automationEnabled,false);assert.equal(f.store.listJobs({}).meta.total,2);});

test("model status exposes configuration booleans without secrets",async t=>{const f=await fixture(t);const r=await f.app.inject({method:"GET",url:"/api/v1/ai-models/status",headers:auth});assert.equal(r.statusCode,200,r.body);assert.deepEqual(r.json().data,{provider:"mock",adapterConfigured:true,endpointConfigured:true,apiKeyConfigured:true,transportConfigured:true,summaryModelConfigured:true,memoryExtractionModelConfigured:true});assert.doesNotMatch(r.body,/admin-secret|p4b-token|fake-key/);});

test("admin-only manual model test uses fake adapter and creates no AI job",async t=>{const f=await fixture(t,[JSON.stringify({ok:true})]);for(const headers of [{},auth,{authorization:`Basic ${Buffer.from("admin:wrong").toString("base64")}`}]){const denied=await f.app.inject({method:"POST",url:"/admin/ai/models/test",headers,payload:{feature:"summary"}});assert.equal(denied.statusCode,401)}const headers={authorization:`Basic ${Buffer.from("admin:admin-secret").toString("base64")}`};const r=await f.app.inject({method:"POST",url:"/admin/ai/models/test",headers,payload:{feature:"summary"}});assert.equal(r.statusCode,200,r.body);assert.deepEqual(r.json().data,{feature:"summary",provider:"mock",configured:true,responseValid:true});assert.equal(f.adapter.inputs.length,1);assert.equal(f.adapter.inputs[0].model,"mock-s");assert.deepEqual(f.adapter.inputs[0].input,{operation:"configuration_test"});assert.equal(f.store.listJobs({}).meta.total,0);});
