"use strict";
const assert=require("node:assert/strict");const fs=require("node:fs"),os=require("node:os"),path=require("node:path");const {test}=require("node:test");
const {openDatabase}=require("../database");const {SessionStore}=require("../session-store");const {StructuredMemoryStore}=require("../structured-memory-store");const {AiMemoryStore}=require("../ai-memory-store");const {ConversationSummaryService}=require("../conversation-summary-service");const {AiTaskRunner}=require("../ai-task-runner");

class MockAdapter{constructor(outputs=[]){this.outputs=[...outputs];this.inputs=[];this.configured=true}isConfigured(){return this.configured}async generate(input){this.inputs.push(input);const next=this.outputs.shift();if(next instanceof Error)throw next;const value=typeof next==="function"?await next(input):next;if(value&&typeof value==="object"&&"content" in value)return value;return{content:value,usage:null,model:input.model,latencyMs:0}}}
async function fixture(t,outputs=[],config={}){const dir=await fs.promises.mkdtemp(path.join(os.tmpdir(),"p4b-ai-"));const connection=openDatabase(path.join(dir,"db.sqlite"));const sessions=new SessionStore({database:connection.db,filename:connection.filename});const memories=new StructuredMemoryStore({database:connection.db,filename:connection.filename});const store=new AiMemoryStore({database:connection.db,memoryStore:memories});const adapter=new MockAdapter(outputs);const service=new ConversationSummaryService({database:connection.db,store,adapter,summaryModel:"mock-summary",extractionModel:"mock-memory",provider:"mock"});const runner=new AiTaskRunner({store,service,config:{maxAttempts:1,timeoutMs:1000,concurrency:1,summaryModel:"mock-summary",extractionModel:"mock-memory",automationEnabled:false,summaryEnabled:false,extractionEnabled:false,...config}});t.after(async()=>{runner.stop();connection.db.close();await fs.promises.rm(dir,{recursive:true,force:true})});return{connection,sessions,memories,store,adapter,service,runner};}
const add=(sessions,id,content,type="text",thinking=null)=>sessions.addMessage(id,"user",content,"completed",{type,thinking});

test("first, incremental and forced summaries supersede safely without Thinking text",async t=>{const f=await fixture(t,[JSON.stringify({summary:"第一版",coveredUntilMessageId:2}),JSON.stringify({summary:"增量版",coveredUntilMessageId:3}),JSON.stringify({summary:"强制版",coveredUntilMessageId:3})]);const s=f.sessions.createSession("summary");add(f.sessions,s.id,"用户正文");f.sessions.addMessage(s.id,"assistant","回复","completed",{thinking:"绝密思考"});let out=await f.runner.run("session_summary",s.id);assert.equal(out.result.summary.summary,"第一版");assert.equal(f.adapter.inputs[0].input.messages[1].thinkingPresent,true);assert.doesNotMatch(JSON.stringify(f.adapter.inputs[0].input),/绝密思考/);add(f.sessions,s.id,"新消息");out=await f.runner.run("session_summary",s.id);assert.equal(out.result.summary.summary,"增量版");assert.equal(f.adapter.inputs[1].input.previousSummary,"第一版");out=await f.runner.run("session_summary",s.id,{force:true});assert.equal(out.result.summary.summary,"强制版");assert.equal(f.connection.db.prepare("SELECT COUNT(*) n FROM session_summaries WHERE status='superseded'").get().n,2);});

test("no new messages preserves summary; invalid and oversized model output never replace it",async t=>{const f=await fixture(t,[JSON.stringify({summary:"有效",coveredUntilMessageId:1}),"not-json",JSON.stringify({summary:"x".repeat(12001),coveredUntilMessageId:1})]);const s=f.sessions.createSession("safe");add(f.sessions,s.id,"one");await f.runner.run("session_summary",s.id);const unchanged=await f.service.generateSummary(s.id);assert.equal(unchanged.unchanged,true);await assert.rejects(f.runner.run("session_summary",s.id,{force:true}),/有效 JSON/);assert.equal(f.store.activeSummary(s.id).summary,"有效");await assert.rejects(f.runner.run("session_summary",s.id,{force:true}),/长度/);assert.equal(f.store.activeSummary(s.id).summary,"有效");});

test("image and Sticker become safe text metadata",async t=>{const f=await fixture(t,[JSON.stringify({summary:"媒体摘要",coveredUntilMessageId:2})]);const s=f.sessions.createSession("media");add(f.sessions,s.id,"图片说明", "image");add(f.sessions,s.id,"[Sticker: 挥手]","sticker");await f.runner.run("session_summary",s.id);const messages=f.adapter.inputs[0].input.messages;assert.equal(messages[0].content,"图片说明");assert.match(messages[1].content,/Sticker/);assert.doesNotMatch(JSON.stringify(messages),/base64|image\/png/);});

test("candidate validation, empty output, hashes and formal-memory dedupe",async t=>{const valid={type:"MEMORY",title:"偏好",content:"喜欢安静的雨天",occurredAt:null,importance:4,confidence:.8,reason:"明确表达"};const f=await fixture(t,[JSON.stringify({candidates:[valid]}),JSON.stringify({candidates:[valid]}),JSON.stringify({candidates:[]})]);const s=f.sessions.createSession("extract");add(f.sessions,s.id,"喜欢安静的雨天");let out=await f.runner.run("memory_extraction",s.id);assert.equal(out.result.candidates.length,1);out=await f.runner.run("memory_extraction",s.id);assert.equal(out.result.candidates.length,0);assert.equal(out.result.duplicates.length,1);out=await f.runner.run("memory_extraction",s.id);assert.deepEqual(out.result.candidates,[]);for(const bad of [{...valid,type:"BAD"},{...valid,importance:6},{...valid,confidence:2},{...valid,title:"x".repeat(201)}])assert.throws(()=>f.store.insertCandidates(s.id,[bad]),/无效|1 到 5|0 到 1|不能超过/);f.memories.create({type:"MEMORY",content:"正式重复"});const dup=f.store.insertCandidates(s.id,[{...valid,content:"正式重复"}]);assert.equal(dup.candidates.length,0);assert.equal(dup.duplicates[0].memoryId!==null,true);});

test("approve transaction, duplicate approve, reject, reopen, delete and rollback",async t=>{const f=await fixture(t);const s=f.sessions.createSession("review");const [candidate]=f.store.insertCandidates(s.id,[{type:"NOTE",title:"候选",content:"需要审核",importance:3,confidence:.5,reason:"test"}]).candidates;const approved=f.store.approveCandidate(candidate.id,{title:"人工编辑"},"reviewer");assert.equal(approved.status,"approved");assert.ok(approved.approvedMemoryId);await assert.rejects(async()=>f.store.approveCandidate(candidate.id),/已经批准/);const [other]=f.store.insertCandidates(s.id,[{type:"EVENT",content:"另一个候选",importance:2}]).candidates;assert.equal(f.store.setCandidateStatus(other.id,"reject").status,"rejected");assert.equal(f.store.setCandidateStatus(other.id,"reopen").status,"pending");assert.equal(f.store.deleteCandidate(other.id).status,"deleted");const [rollback]=f.store.insertCandidates(s.id,[{type:"NOTE",content:"事务失败候选"}]).candidates;const original=f.memories.create.bind(f.memories);f.memories.create=()=>{throw new Error("forced")};assert.throws(()=>f.store.approveCandidate(rollback.id),/forced/);f.memories.create=original;assert.equal(f.store.getCandidate(rollback.id).status,"pending");});

test("candidate pagination filters keyword and Session deletion SET NULL",async t=>{const f=await fixture(t);const s=f.sessions.createSession("filter");f.store.insertCandidates(s.id,[{type:"MEMORY",content:"alpha keyword"},{type:"EVENT",content:"beta"}]);assert.equal(f.store.listCandidates({page:1,limit:1,status:"pending"}).items.length,1);assert.equal(f.store.listCandidates({keyword:"alpha",type:"MEMORY"}).meta.total,1);f.sessions.deleteSession(s.id);assert.equal(f.store.listCandidates({status:"pending"}).items.every(x=>x.sessionId===null),true);});

test("job conflict, cancellation, timeout, attempts and automation disabled",async t=>{const f=await fixture(t,[({signal})=>new Promise((resolve,reject)=>{signal.addEventListener("abort",()=>reject(Object.assign(new Error("aborted"),{name:"AbortError"})));setTimeout(()=>resolve(JSON.stringify({summary:"late",coveredUntilMessageId:1})),500)}),({signal})=>new Promise((resolve,reject)=>signal.addEventListener("abort",()=>reject(new Error("timeout"))))],{timeoutMs:40});const s=f.sessions.createSession("jobs");add(f.sessions,s.id,"one");assert.deepEqual(f.runner.evaluateSession(s.id),[]);const pending=f.runner.run("session_summary",s.id);await new Promise(r=>setTimeout(r,10));const running=f.store.listJobs({status:"running"}).items[0];f.runner.cancel(running.id);const cancelled=await pending;assert.equal(cancelled.job.status,"cancelled");await assert.rejects(f.runner.run("session_summary",s.id),error=>error.code==="AI_JOB_TIMEOUT");assert.equal(f.store.listJobs({status:"failed"}).items[0].attemptCount,1);});

test("missing model and missing adapter are explicit and do not create jobs",async t=>{const f=await fixture(t,[],{summaryModel:""});const s=f.sessions.createSession("disabled");add(f.sessions,s.id,"one");await assert.rejects(f.runner.run("session_summary",s.id),error=>error.code==="AI_MODEL_NAME_MISSING");assert.equal(f.store.listJobs({}).meta.total,0);f.service.adapter.configured=false;await assert.rejects(f.service.extractCandidates(s.id),error=>error.code==="AI_MODEL_NOT_CONFIGURED");});

test("jobs expose all states and enforce same-session conflicts",async t=>{const f=await fixture(t,[JSON.stringify({summary:"done",coveredUntilMessageId:1})]);const s=f.sessions.createSession("states");add(f.sessions,s.id,"one");const queued=f.store.createJob("memory_extraction",s.id,1,"mock","mock-m");assert.equal(queued.status,"queued");assert.equal(f.store.updateJob(queued.id,"running",{attemptCount:1}).status,"running");assert.throws(()=>f.store.createJob("memory_extraction",s.id,1,"mock","mock-m"),error=>error.code==="AI_JOB_CONFLICT");assert.equal(f.store.updateJob(queued.id,"failed",{errorCode:"TEST"}).status,"failed");const cancel=f.store.createJob("memory_extraction",s.id,1,"mock","mock-m");assert.equal(f.store.cancelJob(cancel.id).status,"cancelled");assert.equal((await f.runner.run("session_summary",s.id)).job.status,"completed");});

test("maximum attempts are bounded",async t=>{const first=Object.assign(new Error("upstream one"),{code:"UPSTREAM"}),second=Object.assign(new Error("upstream two"),{code:"UPSTREAM"});const f=await fixture(t,[first,second],{maxAttempts:2});const s=f.sessions.createSession("attempts");add(f.sessions,s.id,"one");await assert.rejects(f.runner.run("session_summary",s.id),/upstream two/);const job=f.store.listJobs({status:"failed"}).items[0];assert.equal(job.attemptCount,2);assert.equal(f.adapter.inputs.length,2);});

test("completed jobs are linked to their summary and candidate products",async t=>{const candidate={type:"NOTE",content:"审计候选",importance:3};const f=await fixture(t,[JSON.stringify({summary:"审计摘要",coveredUntilMessageId:1}),JSON.stringify({candidates:[candidate]})]);const s=f.sessions.createSession("audit");add(f.sessions,s.id,"one");const summaryOut=await f.runner.run("session_summary",s.id);assert.equal(summaryOut.job.status,"completed");assert.equal(summaryOut.result.summary.sourceJobId,summaryOut.job.id);assert.equal(f.connection.db.prepare("SELECT source_job_id FROM session_summaries WHERE id=?").get(summaryOut.result.summary.id).source_job_id,summaryOut.job.id);const candidateOut=await f.runner.run("memory_extraction",s.id);assert.equal(candidateOut.job.status,"completed");assert.equal(candidateOut.result.candidates[0].sourceJobId,candidateOut.job.id);assert.equal(f.connection.db.prepare("SELECT source_job_id FROM memory_candidates WHERE id=?").get(candidateOut.result.candidates[0].id).source_job_id,candidateOut.job.id);});

test("runner persists adapter model usage and latency on completed jobs",async t=>{const f=await fixture(t,[{content:JSON.stringify({summary:"带计量摘要",coveredUntilMessageId:1}),usage:{prompt_tokens:11,completion_tokens:5,total_tokens:16},model:"actual-summary-model",latencyMs:37}]);const s=f.sessions.createSession("metrics");add(f.sessions,s.id,"one");const out=await f.runner.run("session_summary",s.id);const row=f.connection.db.prepare("SELECT model,prompt_tokens,completion_tokens,total_tokens,latency_ms FROM ai_jobs WHERE id=?").get(out.job.id);assert.deepEqual({...row},{model:"actual-summary-model",prompt_tokens:11,completion_tokens:5,total_tokens:16,latency_ms:37});});
