"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const Fastify=require("fastify"),{JSDOM}=require("jsdom");
const {PersonalizationStore,validateSection}=require("../personalization-store");
const {registerPersonalizationRoutes}=require("../personalization-routes");
const {SyncClient,KEY}=require("../frontend-p4b/assets/js/personalization-sync");
const Prefs=require("../ai-companion-frontend/storage/user-preference-store"),Themes=require("../frontend-p4b/assets/js/theme-store"),Voice=require("../frontend-p4b/assets/js/voice-adapter");
const id="11111111-1111-4111-8111-111111111111",id2="22222222-2222-4222-8222-222222222222",url=`/api/theme/assets/${id}`,url2=`/api/theme/assets/${id2}`;
const pick=(v,keys)=>Object.fromEntries(keys.map(k=>[k,v[k]]));
const theme=()=>pick(Themes.normalizeTheme(Themes.DEFAULT_THEME),["id","name","source","accentMode","accentExplicit","harmonyVersion","migratedVisualSlotsSafe","tokens","assets","visualSlots","customDesign","layout"]);
const initial=()=>({sections:{identity:{userAvatar:{imageData:url,crop:{x:23,y:61},scale:1.4},chenAvatar:{imageData:url2,crop:{x:60,y:30},scale:1.2}},appearance:{chatBackground:{imageData:url,position:"center",size:"cover",overlay:.35},activeTheme:theme(),ui:{mode:"night",style:"purple",font:"default"}},voicePortable:{autoRead:false,rate:1,pitch:1,volume:1,recognitionLanguage:"zh-CN",showInterimTranscript:true,voiceSession:{continuousConversation:false,autoSpeak:true,backgroundMode:"follow-chat",backgroundAssetId:""}}}});
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"personalization-v79-")),events=[],assets=new Set([id,id2]);const store=new PersonalizationStore({rootDir:path.join(dir,"settings"),eventStore:{create:(...args)=>events.push(args)},assetStore:{resolve:id=>{if(!assets.has(id))throw Error("missing");return {};}}});const app=Fastify({logger:false});registerPersonalizationRoutes(app,{store,apiKey:"fake-test-key"});await app.ready();t.after(async()=>{await app.close();fs.rmSync(dir,{recursive:true,force:true});});const calls=[];const request=async(route,options={})=>{calls.push([route,options.method||"GET"]);const response=await app.inject({url:route,method:options.method||"GET",headers:{authorization:"Bearer fake-test-key","content-type":"application/json"},...(options.body?{payload:options.body}:{})});const payload=response.json();if(response.statusCode>=400)throw Object.assign(Error(payload.error.code),{status:response.statusCode,code:payload.error.code});return payload;};return {store,app,events,assets,request,calls,dir};}
function browser(t,f){const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:"https://example.test"}),storage=dom.window.localStorage,prefs=new Prefs.UserPreferenceStore({storage,eventTarget:null}),themes=new Themes.ThemeStore({storage,documentRef:dom.window.document}),voice=new Voice.VoiceSettingsStore(storage);const appearance={read:()=>JSON.parse(storage.getItem("xinban-appearance")||"{}"),save:v=>storage.setItem("xinban-appearance",JSON.stringify(v))};let uploads=0;const backup={snapshots:new Map(),ensure:async identity=>{JSON.parse(storage.getItem("personalization-original-avatars-v79")||"[]");const id=JSON.stringify(identity);backup.snapshots.set(id,structuredClone(identity));return {id};}};const client=new SyncClient({backup,preferences:prefs,themes,voice,appearance,storage,request:f.request,upload:async()=>{uploads++;return url;}});t.after(()=>dom.window.close());return {dom,storage,prefs,themes,voice,client,uploads:()=>uploads};}

test("GET empty is read-only and creates no directory",async t=>{const f=await fixture(t);assert.deepEqual((await f.request("/api/personalization")).data,{initialized:false,state:null});assert.equal(fs.existsSync(f.store.rootDir),false);});
test("explicit bootstrap persists version and independent section metadata with private permissions",async t=>{const f=await fixture(t);const value=f.store.bootstrap(initial());assert.equal(value.state.revision,1);for(const section of Object.values(value.state.sections))assert.equal(section.revision,1);assert.equal(fs.statSync(f.store.rootDir).mode&0o777,0o700);assert.equal(fs.statSync(f.store.filename).mode&0o777,0o600);assert.deepEqual(fs.readdirSync(f.store.rootDir),["state.json"]);});
test("second bootstrap rejected without replacing state",async t=>{const f=await fixture(t);f.store.bootstrap(initial());assert.throws(()=>f.store.bootstrap(initial()),e=>e.code==="ALREADY_INITIALIZED");assert.equal(f.store.read().revision,1);});
for(const section of ["identity","appearance","voicePortable"])test(`PATCH ${section} increments only its own revision`,async t=>{const f=await fixture(t);f.store.bootstrap(initial());const before=f.store.read(),patch=initial().sections[section];f.store.patch({section,baseRevision:1,patch});const after=f.store.read();assert.equal(after.revision,2);for(const name of Object.keys(before.sections))if(name===section)assert.equal(after.sections[name].revision,2);else assert.deepEqual(after.sections[name],before.sections[name]);});
test("stale baseRevision returns 409 and leaves event count unchanged",async t=>{const f=await fixture(t);f.store.bootstrap(initial());f.store.patch({section:"identity",baseRevision:1,patch:{userAvatar:null}});await assert.rejects(f.request("/api/personalization",{method:"PATCH",body:JSON.stringify({section:"identity",baseRevision:1,patch:{chenAvatar:null}})}),e=>e.status===409);assert.equal(f.events.length,2);});
test("all personalization routes enforce current Bearer authentication including local requests",async t=>{const f=await fixture(t);for(const [method,url] of [["GET","/api/personalization"],["PATCH","/api/personalization"],["POST","/api/personalization/bootstrap"]]){const response=await f.app.inject({method,url,payload:method==="GET"?undefined:{}});assert.equal(response.statusCode,401);assert.equal(response.headers["cache-control"],"no-store");assert.doesNotMatch(response.body,/fake-test-key/);}});
for(const value of [null,[],{section:"identity",baseRevision:"1",patch:{}},{section:"identity",baseRevision:1,patch:{secret:"x"}},{section:"unknown",baseRevision:1,patch:{}}])test(`malformed PATCH rejected: ${JSON.stringify(value)}`,async t=>{const f=await fixture(t);assert.throws(()=>f.store.patch(value));});
for(const value of ["javascript:alert(1)","data:image/png;base64,AAAA","blob:abc","file:///x","https://example.com/a.png","http://x/a","/tmp/image.png","/home/image.png","//evil/a","/api/theme/assets/../secret"])test(`dangerous asset rejected ${value.split(":")[0]}`,()=>{assert.throws(()=>validateSection("identity",{userAvatar:{imageData:value}}));});
for(const key of ["token","password","Authorization","apiKey","GATEWAY_API_KEY","TARGET_API_KEY","voiceURI","voiceName"])test(`secret or device-local field rejected: ${key}`,()=>{assert.throws(()=>validateSection("voicePortable",{[key]:"private"}));});
test("arbitrary CSS, selectors and unknown nested design fields rejected",()=>{for(const patch of [{...theme(),customCss:"body{display:none}"},{...theme(),tokens:{selector:"body"}},{...theme(),customDesign:{version:1,regions:{"chat.page":{selector:"body"}}}}])assert.throws(()=>validateSection("appearance",{activeTheme:patch}));});
test("safe customDesign and visualSlots round-trip with references only",()=>{const input=theme();input.visualSlots={...input.visualSlots,enabledByUser:true,pageBackground:{...input.visualSlots.pageBackground,enabled:true,url}};input.customDesign={version:1,regions:{"home.hero":{enabled:true,radius:24,image:{enabled:true,url:url2}}}};const data=validateSection("appearance",{activeTheme:input});assert.equal(data.activeTheme.visualSlots.pageBackground.url,url);assert.equal(data.activeTheme.customDesign.regions["home.hero"].image.url,url2);assert.equal(data.activeTheme.assetLibrary,undefined);});
test("missing assets rejected without writing new section or event",async t=>{const f=await fixture(t);f.assets.delete(id);assert.throws(()=>f.store.bootstrap(initial()),e=>e.code==="PERSONALIZATION_ASSET_MISSING");assert.equal(f.events.length,0);assert.equal(f.store.read(),null);});
test("asset reference deletion protection includes avatar, theme and voice background",async t=>{const f=await fixture(t);const input=initial();input.sections.voicePortable.voiceSession.backgroundAssetId=id2;f.store.bootstrap(input);assert.equal(f.store.findAssetReferences(id).length,1);assert.equal(f.store.findAssetReferences(id2).length,1);assert.match(fs.readFileSync("theme-asset-routes.js","utf8"),/THEME_ASSET_REFERENCED_BY_PERSONALIZATION/);});
test("EventStore facts contain revisions, never personalization bodies",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const [event,source]=f.events[0];assert.equal(event.eventType,"personalization.initialized");assert.equal(source.source,"personalization-store");assert.deepEqual(Object.keys(event.payload).sort(),["revision","section","sectionRevision"]);});
test("new store instance reads existing state; repeat reads are idempotent",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const next=new PersonalizationStore({rootDir:f.store.rootDir});assert.deepEqual(next.get(),f.store.get());assert.deepEqual(next.get(),next.get());});
test("corrupt state fails closed rather than permitting second initialization",async t=>{const f=await fixture(t);f.store.bootstrap(initial());fs.writeFileSync(f.store.filename,"{");assert.throws(()=>f.store.get(),e=>e.statusCode===503);assert.throws(()=>f.store.bootstrap(initial()));});
test("old localStorage is a candidate and never automatically uploaded",async t=>{const f=await fixture(t),b=browser(t,f);b.prefs.saveAvatar({imageData:"data:image/png;base64,AAAA",crop:{x:20,y:30}},"user");const before=b.storage.getItem(Prefs.STORAGE_KEY);await b.client.start();assert.equal(b.client.status,"uninitialized");assert.equal(b.client.capture().identity.userAvatar.crop.x,20);assert.equal(b.uploads(),0);assert.ok(f.calls.every(([,method])=>method==="GET"));assert.equal(b.storage.getItem(Prefs.STORAGE_KEY),before);});
test("explicit bootstrap uploads legacy images via existing asset API and preserves old keys",async t=>{const f=await fixture(t),b=browser(t,f);b.prefs.saveAvatar({imageData:"data:image/png;base64,AAAA"},"user");await b.client.start();await b.client.bootstrap();assert.equal(b.client.status,"synced");assert.equal(b.uploads(),1);assert.equal(f.store.read().sections.identity.data.userAvatar.imageData,url);assert.ok(b.storage.getItem(Prefs.STORAGE_KEY));assert.equal(JSON.parse(b.storage.getItem(KEY)).initialized,true);});
test("cloud exists: stale local preferences do not bootstrap or PATCH",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const b=browser(t,f);b.prefs.saveAvatar({imageData:url2},"user");await b.client.start();assert.equal(b.prefs.getUserAvatarImage(),url);assert.ok(f.calls.every(([,method])=>method==="GET"));await b.client.bootstrap();assert.equal(f.store.read().revision,1);});
test("two device avatar update uses existing preference store and retains crop",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const a=browser(t,f),b=browser(t,f);await a.client.start();a.prefs.saveAvatar({imageData:url2,crop:{x:12,y:78},scale:1.6},"user");a.client.changed();await a.client.sync();await b.client.start();assert.equal(b.prefs.getUserAvatarImage(),url2);assert.deepEqual(b.prefs.getAvatar("user").crop,{x:12,y:78});assert.equal(b.prefs.getAvatar("user").scale,1.6);});
test("mobile background change does not overwrite desktop avatar section",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const a=browser(t,f),b=browser(t,f);await a.client.start();await b.client.start();a.prefs.saveAvatar({imageData:url2},"user");a.client.changed();b.prefs.saveChatBackground({imageData:url2});b.client.changed();await b.client.sync();await a.client.sync();assert.equal(a.prefs.getChatBackground().image,url2);assert.equal(f.store.read().sections.identity.data.userAvatar.imageData,url2);assert.equal(f.store.read().sections.appearance.revision,2);});
test("active theme selection and appearance enums synchronize without duplicating preset library",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const a=browser(t,f),b=browser(t,f);await a.client.start();a.themes.applyTheme(Themes.PRESET_THEMES[1]);a.client.changed();await a.client.sync();await b.client.start();assert.equal(b.themes.getActive().id,Themes.PRESET_THEMES[1].id);assert.equal(b.uploads(),0);assert.equal(b.storage.getItem(Themes.LIBRARY_KEY),null);});
test("portable voice settings sync; device voices remain untouched",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const a=browser(t,f),b=browser(t,f);b.voice.save({...b.voice.load(),voiceURI:"mobile-voice",voiceName:"Mobile",voiceLang:"ja-JP"});await a.client.start();a.voice.save({...a.voice.load(),rate:1.4,autoRead:true,recognitionLanguage:"en-US",voiceURI:"desktop-voice",voiceSession:{continuousConversation:true,autoSpeak:true,backgroundMode:"custom",backgroundAssetId:id2}});a.client.changed();await a.client.sync();await b.client.start();assert.equal(b.voice.load().rate,1.4);assert.equal(b.voice.load().voiceURI,"mobile-voice");assert.equal(b.voice.load().voiceName,"Mobile");assert.equal(b.voice.load().voiceLang,"ja-JP");assert.equal(b.voice.load().voiceSession.continuousConversation,true);assert.equal(b.voice.load().voiceSession.backgroundAssetId,id2);assert.doesNotMatch(JSON.stringify(f.store.read()),/desktop-voice|mobile-voice/);});
for(const choice of ["cloud","local"])test(`section conflict ${choice} choice is explicit and never silently overwrites`,async t=>{const f=await fixture(t);f.store.bootstrap(initial());const a=browser(t,f),b=browser(t,f);await a.client.start();await b.client.start();a.prefs.saveChatBackground({imageData:url2});a.client.changed();b.prefs.saveChatBackground({imageData:null});b.client.changed();await a.client.sync();await b.client.sync();assert.equal(b.client.status,"conflict");assert.equal(f.store.read().sections.appearance.data.chatBackground.imageData,url2);await b.client.resolve("appearance",choice);assert.equal(b.client.status,"synced");assert.equal(f.store.read().sections.appearance.data.chatBackground.imageData,choice==="cloud"?url2:null);});
test("GET offline preserves visual cache and makes one bounded attempt",async t=>{const f=await fixture(t),b=browser(t,f);b.prefs.saveAvatar({imageData:url},"user");let count=0;b.client.request=async()=>{count++;throw Object.assign(new TypeError("offline"),{code:"SYNC_NETWORK"});};await b.client.start();assert.equal(b.prefs.getUserAvatarImage(),url);assert.equal(b.client.status,"offline");assert.equal(count,1);});
test("PATCH offline retains pending visuals across reload and retry succeeds",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const b=browser(t,f);await b.client.start();b.prefs.saveAvatar({imageData:url2},"user");b.client.changed();b.client.request=async(p,o)=>{if(o?.method==="PATCH")throw Object.assign(new TypeError("offline"),{code:"SYNC_NETWORK"});return f.request(p,o);};await b.client.sync();assert.equal(b.client.status,"pending");assert.equal(b.prefs.getUserAvatarImage(),url2);assert.ok(JSON.parse(b.storage.getItem(KEY)).pending.identity);b.client.request=f.request;await b.client.sync();assert.equal(b.client.status,"synced");assert.equal(f.store.read().sections.identity.data.userAvatar.imageData,url2);});
test("preview-only theme application cannot upload unapplied theme",async t=>{const f=await fixture(t);f.store.bootstrap(initial());const b=browser(t,f);await b.client.start();b.themes.applyTheme(Themes.PRESET_THEMES[1],{persist:false});b.client.changed();assert.equal(Object.keys(b.client.pending).length,0);});
test("v79 shell loads sync on Home Chat Settings and preserves game build",()=>{for(const file of ["index.html","chat.html","settings.html","theme-workshop.html"])assert.match(fs.readFileSync(`frontend-p4b/${file}`,"utf8"),/personalization-boot.js\?v=v79-p4b/);assert.match(fs.readFileSync("frontend-p4b/sw.js","utf8"),/xinban-shell-v79-p4b/);assert.match(fs.readFileSync("ai-companion-frontend/game/game.js","utf8"),/game-v49-p4b/);});

test("bootstrap rejects incomplete sections before persisting",async t=>{const f=await fixture(t),input=initial();input.sections.appearance={};assert.throws(()=>f.store.bootstrap(input));assert.equal(f.store.read(),null);});
test("partial voiceSession PATCH preserves other portable settings",async t=>{const f=await fixture(t);f.store.bootstrap(initial());f.store.patch({section:"voicePortable",baseRevision:1,patch:{voiceSession:{continuousConversation:true}}});assert.deepEqual(f.store.read().sections.voicePortable.data.voiceSession,{continuousConversation:true,autoSpeak:true,backgroundMode:"follow-chat",backgroundAssetId:""});});
test("EventStore failure prevents publishing new state",async t=>{const f=await fixture(t);f.store.eventStore={create:()=>{throw Error("event unavailable");}};assert.throws(()=>f.store.bootstrap(initial()));assert.equal(f.store.read(),null);assert.deepEqual(fs.readdirSync(f.store.rootDir),[]);});
test("cross-origin avatar and theme rendering use existing canonical resolver",()=>{
  const dom=new JSDOM('<!doctype html><html><head></head><body></body></html>',{url:"https://chat.xiaowo.homes",runScripts:"outside-only"}),w=dom.window;
  for(const file of ["frontend-p4b/assets/js/theme-store.js","ai-companion-frontend/storage/user-preference-store.js"])w.eval(fs.readFileSync(file,"utf8"));
  const prefs=new w.CompanionUserPreferences.UserPreferenceStore();prefs.saveAvatar({imageData:url},"user");assert.equal(prefs.getUserAvatarImage(),"https://api.xiaowo.homes"+url);
  const input=JSON.parse(JSON.stringify(w.XinbanThemes.DEFAULT_THEME));input.visualSlots.enabledByUser=true;input.visualSlots.pageBackground.enabled=true;input.visualSlots.pageBackground.url=url;w.XinbanThemeStore.applyTheme(input);assert.ok(w.document.documentElement.style.getPropertyValue("--xb-bg-image").includes("https://api.xiaowo.homes"+url));assert.equal(JSON.parse(w.localStorage.getItem(w.XinbanThemes.ACTIVE_KEY)).visualSlots.pageBackground.url,url);w.close();
});
test("missing canonical chat background safely falls back without changing stored preference",async()=>{
  const dom=new JSDOM('<!doctype html><html><body><div class="chat-shell"></div></body></html>',{url:"https://example.test",runScripts:"outside-only"}),w=dom.window,images=[];
  await new Promise(resolve=>w.document.addEventListener("DOMContentLoaded",resolve,{once:true}));w.Image=class{constructor(){images.push(this);}};
  w.eval(fs.readFileSync("ai-companion-frontend/storage/user-preference-store.js","utf8"));const prefs=new w.CompanionUserPreferences.UserPreferenceStore();prefs.saveChatBackground({imageData:url});w.eval(fs.readFileSync("frontend-p4b/assets/js/chat-preferences.js","utf8"));w.document.dispatchEvent(new w.Event("DOMContentLoaded"));await Promise.resolve();images.at(-1).onerror();assert.equal(w.document.querySelector(".chat-shell").classList.contains("has-chat-background"),false);assert.equal(prefs.getChatBackground().image,url);w.close();
});

test("Gateway and Provider credentials never enter snapshots, wire bodies, cloud, or EventStore",async t=>{
 const f=await fixture(t),b=browser(t,f),secret="fake-private-gateway",third="fake-private-provider";
 b.storage.setItem("xinban-provider-config-v1",JSON.stringify({auth:{token:third},gatewayConnection:{auth:{token:secret}}}));
 const originalLoad=b.voice.load.bind(b.voice);
 b.voice.load=()=>{const v=originalLoad();return {...v,Authorization:secret,gatewayCredential:secret,voiceSession:{...v.voiceSession,token:secret,password:third,apiKey:secret,key:secret,Authorization:third,gatewayConnection:{auth:{token:secret}},voiceURI:secret,voiceName:third}}};
 const safe=value=>{const json=JSON.stringify(value);assert.equal(json.includes(secret),false);assert.equal(json.includes(third),false)};
 const originalRequest=b.client.request;
 b.client.request=async(route,options)=>{if(options?.body)safe(options.body);const payload=await originalRequest(route,options);safe(payload);return payload};
 safe(b.client.capture());await b.client.start();await b.client.bootstrap();assert.equal(b.client.status,"synced");
 b.voice.save({...originalLoad(),rate:1.3});b.client.changed();await b.client.sync();
 safe(f.store.get());safe(f.events);safe(b.storage.getItem(KEY));safe(b.client.capture());
 assert.ok(b.storage.getItem("xinban-provider-config-v1").includes(secret));
 assert.doesNotMatch(fs.readFileSync("frontend-p4b/assets/js/personalization-sync.js","utf8"),/console\.|logger\./);
});

test("bootstrap 400 retains safe stage and code without claiming an upload failure",async t=>{
 const f=await fixture(t),b=browser(t,f);await b.client.start();
 const request=b.client.request;b.client.request=async(route,options)=>{if(route.endsWith('/bootstrap'))throw Object.assign(Error('private body'),{status:400,code:'INVALID_PERSONALIZATION'});return request(route,options);};
 await b.client.bootstrap();assert.deepEqual(b.client.migrationError,{stage:'bootstrap',slot:null,status:400,code:'INVALID_PERSONALIZATION'});assert.equal(b.client.serverInitialized,false);assert.equal(b.client.cloud,null);assert.equal(f.store.read(),null);
});
test("pre-upload capture and backup errors identify the local stage without exposing exception text",async t=>{
 const f=await fixture(t),b=browser(t,f);await b.client.start();const capture=b.client.capture.bind(b.client);
 b.client.capture=()=>{throw Error('private snapshot')};await b.client.bootstrap();assert.deepEqual(b.client.migrationError,{stage:'capture',slot:null,status:null,code:'SYNC_REQUEST_FAILED'});assert.equal(b.uploads(),0);
 b.client.capture=capture;b.prefs.saveAvatar({imageData:url},'user');b.storage.setItem('personalization-original-avatars-v79','{');await b.client.bootstrap();assert.deepEqual(b.client.migrationError,{stage:'avatar-backup',slot:null,status:null,code:'LOCAL_BACKUP_INVALID'});assert.equal(f.calls.some(([route])=>route.endsWith('/bootstrap')),false);
});

for(const code of ['LOCAL_STORAGE_QUOTA_EXCEEDED','INDEXEDDB_QUOTA_EXCEEDED','LOCAL_BACKUP_UNAVAILABLE','LOCAL_BACKUP_INVALID'])test(`avatar backup ${code} preserves originals and prevents all uploads/bootstrap`,async t=>{
 const f=await fixture(t),b=browser(t,f);b.prefs.saveAvatar({imageData:'data:image/png;base64,AAAA',crop:{x:21,y:67,zoom:1.3},scale:1.3},'user');b.prefs.saveAvatar({imageData:'data:image/png;base64,BBBB',crop:{x:42,y:19},scale:1.8},'chen');b.prefs.saveChatBackground({imageData:url});
 const before=b.storage.getItem(Prefs.STORAGE_KEY);b.client.backup={ensure:async()=>{throw Object.assign(Error('private'),{code})}};
 await b.client.bootstrap();await b.client.bootstrap();
 assert.equal(b.client.migrationError.stage,'avatar-backup');assert.equal(b.client.migrationError.code,code);assert.equal(b.client.serverInitialized,false);assert.equal(b.storage.getItem(Prefs.STORAGE_KEY),before);assert.equal(b.uploads(),0);assert.equal(f.calls.filter(([,method])=>method!=='GET').length,0);assert.equal(f.store.read(),null);
});
test('avatar backup is awaited before uploads and preserves original zoom metadata',async t=>{
 const f=await fixture(t),b=browser(t,f);b.prefs.saveAvatar({imageData:'data:image/png;base64,AAAA',crop:{x:21,y:67,zoom:1.3},scale:1.3},'user');let release,started;const entered=new Promise(r=>started=r);
 b.client.backup={ensure:async identity=>{assert.deepEqual(identity.userAvatar.crop,{x:21,y:67,zoom:1.3});started();await new Promise(r=>release=r);}};
 const task=b.client.bootstrap();await entered;assert.equal(b.uploads(),0);assert.equal(f.calls.some(([,method])=>method==='POST'),false);release();await task;assert.equal(b.client.status,'synced');assert.deepEqual(f.store.read().sections.identity.data.userAvatar.crop,{x:21,y:67});
});
test('verified uploads survive failed bootstrap retry in the same client without new assets',async t=>{
 const f=await fixture(t),b=browser(t,f);b.prefs.saveAvatar({imageData:'data:image/png;base64,AAAA'},'user');let reject=true;
 b.client.request=async(route,options)=>{if(reject&&options?.method==='POST')throw Object.assign(Error(),{status:400,code:'INVALID_PERSONALIZATION'});return f.request(route,options);};
 await b.client.bootstrap();assert.equal(b.uploads(),1);reject=false;await b.client.bootstrap();assert.equal(b.uploads(),1);assert.equal(b.client.backup.snapshots.size,1);assert.equal(b.client.status,'synced');
});
test('invalid upload response is not retained for retries',async t=>{
 const f=await fixture(t),b=browser(t,f);b.prefs.saveAvatar({imageData:'data:image/png;base64,AAAA'},'user');let count=0;b.client.upload=async()=>++count===1?'blob:temporary':url;
 await b.client.bootstrap();assert.equal(b.client.images.size,0);assert.equal(f.store.read(),null);await b.client.bootstrap();assert.equal(count,2);assert.equal(b.client.status,'synced');
});
