"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{test}=require("node:test"),themes=require("../frontend-p4b/assets/js/theme-store.js");
const root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8"),js=read("frontend-p4b/assets/js/theme-workshop.js"),html=read("frontend-p4b/theme-workshop.html"),css=read("frontend-p4b/assets/css/theme-workshop.css");
test("v71 organization UI exposes tags notes recent filters and details",()=>{for(const token of ["data-asset-batch-tag=\"add\"","data-asset-batch-tag=\"remove\"","data-design-asset-page","data-design-asset-region","data-filter=\"recent\"","data-filter=\"duplicate\"","data-asset-details-note","data-asset-details-use"])assert.match(html,new RegExp(token));assert.match(css,/design-asset-details/u);assert.match(js,/assetVisibleLimit=48/u);assert.match(js,/setTimeout\([\s\S]{0,120}160/u);assert.match(js,/tokens\.every\(token=>text\.includes\(token\)\)/u);assert.doesNotMatch(js,/\.innerHTML\s*=/u);});
test("v71 page and region filtering derives labels from DESIGN_REGIONS",()=>{assert.match(js,/Object\.entries\(api\.DESIGN_REGIONS\)/u);assert.match(js,/ref\.key\?\.startsWith/u);assert.match(js,/ref\.key===region/u);assert.match(js,/!ref\.scope\.startsWith\("保存主题"\)/u);assert.equal(themes.DESIGN_REGIONS["chat.assistantBubble"],"聊天 · 沉气泡");});
test("v71 selected assets alone mark recent use and manager details remain safe",()=>{assert.match(js,/chooseLibraryAsset[\s\S]{0,700}markAssetUsed\(asset\)/u);const render=js.slice(js.indexOf("const renderDesignAssets=()=>"),js.indexOf("const openPicker="));assert.doesNotMatch(render,/markAssetUsed|\/used/u);assert.match(js,/hidden=assetPickerTarget\.type!=="manager"/u);});
test("v71 picker context filter describes its actual global-recent or current-region logic",()=>{assert.match(html,/data-filter="context">最近使用或当前区域</u);assert.doesNotMatch(html,/最近在此区域使用/u);assert.match(js,/assetFilter==="context"&&\(asset\.lastUsedAt\|\|currentUsage\(asset\)\.some\(ref=>ref\.key===selectedDesignRegion\)\)/u);});
test("v71 exact duplicates use incremental authenticated scan and never auto delete",()=>{assert.match(js,/duplicates\/scan/u);assert.match(js,/duplicateIds/u);const scan=js.slice(js.indexOf("const scanDuplicates"),js.indexOf("const renderDesignAssets="));assert.doesNotMatch(scan,/DELETE|deleteAsset/u);});
test("v71 duplicate scan is user-triggered, single-flight, and reports each batch",()=>{assert.match(js,/if\(duplicateScanInFlight\)return/u);assert.match(js,/finally\{duplicateScanInFlight=false/u);assert.match(js,/已处理.*剩余/u);assert.doesNotMatch(js,/setInterval[\s\S]*duplicates\/scan/u);});
