"use strict";

const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8"),html=read("frontend-p4b/theme-workshop.html"),js=read("frontend-p4b/assets/js/theme-workshop.js"),css=read("frontend-p4b/assets/css/theme-workshop.css")+read("frontend-p4b/assets/css/theme-editor.css");

test("v68 replaces name-only slot selection with the shared visual library",()=>{assert.match(js,/theme-slot-thumb/u);assert.match(js,/choose\.textContent="选择素材"/u);assert.match(js,/assetPickerTarget=\{type:"slot",key\}/u);assert.match(js,/chooseLibraryAsset/u);assert.match(html,/统一素材库/u);assert.doesNotMatch(js,/option\.textContent\s*=\s*asset\.kind/u);});
test("v68 library renders real thumbnails, metadata, usage, filters and checkerboard",()=>{for(const token of ["data-design-asset-search","data-design-asset-sort","data-design-asset-unused","data-filter=\"header\"","data-filter=\"nav\""])assert.ok(html.includes(token),token);assert.match(js,/design-asset-thumb checkerboard/u);assert.match(js,/img\.naturalWidth/u);assert.match(js,/asset\.id\.slice\(0,8\)/u);assert.match(js,/使用中/u);assert.match(css,/checkerboard/u);});
test("v68 page and component regions have explicit preview targets",()=>{const themes=require("../frontend-p4b/assets/js/theme-store.js");for(const target of Object.keys(themes.DESIGN_REGIONS))assert.match(html,new RegExp(`data-design-preview-region="${target.replace(".","\\.")}"`,"u"),target);assert.match(js,/const imageUrl=safeAssetImage\(region\.image\.url\)/u);});
test("v68 selecting a library asset immediately enables only a localized image",()=>{assert.match(js,/region\.image\.url=asset\.url;region\.image\.enabled=true/u);assert.match(js,/safeAssetImage\(asset\.url\)/u);assert.doesNotMatch(js,/region\.image\.url\s*=\s*(?:sourceUrl|pendingUrlImport\.sourceUrl)/u);assert.match(js,/图片状态：✓ 已加载/u);});
test("v68 URL import enforces preview then localize before adding to the theme",()=>{const start=js.indexOf("data-design-url-preview-button"),preview=js.indexOf('gatewayRequest("/api/theme/assets/preview"',start),localize=js.indexOf('gatewayRequest("/api/theme/assets/localize"',preview),push=js.indexOf("next.assetLibrary.push(asset)",localize);assert.ok(start>-1&&preview>start&&localize>preview&&push>localize);assert.match(js,/url:item\.localUrl/u);assert.match(html,/生成预览/u);assert.match(html,/保存到素材库/u);});
test("v68 does not pretend direct upload exists without an approved write route",()=>{assert.match(html,/disabled title="安全上传接口尚未开放">上传图片/u);assert.doesNotMatch(js,/\/api\/theme\/assets\/upload/u);assert.doesNotMatch(read("theme-asset-routes.js"),/\/api\/theme\/assets\/upload/u);});
