"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{test}=require("node:test"),themes=require("../frontend-p4b/assets/js/theme-store.js");
const root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8"),js=read("frontend-p4b/assets/js/theme-workshop.js"),html=read("frontend-p4b/theme-workshop.html"),css=read("frontend-p4b/assets/css/theme-workshop.css"),asset="/api/theme/assets/11111111-1111-4111-8111-111111111111";
test("v69 my assets reuses the unified server-backed picker and upload flow",()=>{assert.match(html,/data-open-asset-manager/u);assert.match(html,/data-design-upload-input/u);assert.match(html,/image\/png,image\/jpeg,image\/webp/u);assert.match(js,/gatewayRequest\(`\/api\/theme\/assets\/library/u);assert.match(js,/gatewayRequest\("\/api\/theme\/assets\/upload"/u);assert.match(js,/new FormData\(\)/u);assert.match(js,/serverAssets/u);assert.match(js,/region\.enabled=true;region\.image=/u);assert.match(css,/checkerboard/u);assert.doesNotMatch(html,/安全上传接口尚未开放/u);});
test("v69 reference collector finds formal theme structures without scanning raw localStorage",()=>{const refs=themes.collectThemeAssetReferences(asset,{activeTheme:{assets:{backgroundImage:asset}},currentTheme:{visualSlots:{pageBackground:{url:asset}},customDesign:{regions:{"home.hero":{image:{url:asset}}}}},draft:{customDesign:{regions:{"chat.page":{image:{url:asset}}}}},savedThemes:[{name:"蓝色主题",customDesign:{regions:{"chat.assistantBubble":{image:{url:asset}}}}}]});assert.equal(refs.length,5);assert.ok(refs.some(x=>x.scope==="当前主题"));assert.ok(refs.some(x=>x.scope==="当前草稿"));assert.ok(refs.some(x=>x.scope.includes("蓝色主题")));assert.match(js,/referencesFor/u);assert.match(js,/if\(references\.length\)\{showReferences\(references\);return;\}/u);assert.doesNotMatch(js,/JSON\.stringify\(localStorage\)\.includes/u);});
test("v69 metadata editing and guarded soft-delete APIs stay authenticated",()=>{assert.match(js,/method:"PATCH"/u);assert.match(js,/method:"DELETE"/u);assert.match(js,/保存名称\/分类/u);assert.match(html,/data-asset-delete-blocked/u);assert.match(js,/主题素材接口认证失败/u);});
test("v69 cached selected images report their loaded dimensions",()=>{assert.match(js,/serverAssets\.find\(item=>item\.url===image\.url\)/u);assert.match(js,/img\.addEventListener\("load",[\s\S]{0,300}img\.src=src;[\s\S]{0,300}asset\.width&&asset\.height\?`图片状态：✓ 已加载/u);});
test("v69 preview background layer remains above the region paint",()=>{const editor=read("frontend-p4b/assets/css/theme-editor.css");assert.match(editor,/data-layer="background"\]\{z-index:0\}/u);assert.doesNotMatch(editor,/data-layer="background"\]\{z-index:-1\}/u);assert.match(editor,/data-layer="front"\]\{z-index:3\}/u);});
test("v69 selected region content can initiate image dragging",()=>{assert.match(js,/let layer=event\.target\.closest\("\.advanced-preview__image-layer"\)/u);assert.match(js,/selected\.dataset\.designPreviewRegion!==selectedDesignRegion/u);assert.match(js,/selected\.querySelector\(":scope > \.advanced-preview__image-layer"\)/u);assert.match(js,/dragSurface=event\.target instanceof Element\?event\.target:layer/u);assert.match(js,/dragSurface\.setPointerCapture/u);});
