"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),test=require("node:test"),Fastify=require("fastify");
const {ThemePresetStore,SHARE_CODE}=require("../theme-preset-service"),{registerThemePresetRoutes}=require("../theme-preset-routes"),themes=require("../frontend-p4b/assets/js/theme-store");
const ASSET="11111111-1111-4111-8111-111111111111",asset=id=>`/api/theme/assets/${id}`;
const theme=(url=asset(ASSET))=>({...themes.DEFAULT_THEME,name:"分享测试",assets:{...themes.DEFAULT_THEME.assets,backgroundImage:url},customCss:""});
function fixture(t){const rootDir=fs.mkdtempSync(path.join(os.tmpdir(),"theme-share-v74-")),events=[],existing=new Set([ASSET]);let tick=0;const clock=()=>new Date(Date.UTC(2026,7,23,12,0,tick++));t.after(()=>fs.rmSync(rootDir,{recursive:true,force:true}));const store=new ThemePresetStore({rootDir,assetStore:{list:()=>[...existing].map(id=>({id}))},eventStore:{create(input,context){events.push({input,context});}},clock});return{store,events,existing};}
const create=store=>store.create({name:"月光玻璃",description:"安静的分享主题",tags:["月光","玻璃"],coverAssetId:ASSET,mood:"宁静",style:"glass",colorProfile:"冷色",theme:theme()});

test("v74 generates unique unguessable share codes without exposing preset ids",t=>{const f=fixture(t),one=create(f.store),two=f.store.create({name:"晨光",theme:theme("")}),sharedOne=f.store.enableShare(one.id),sharedTwo=f.store.enableShare(two.id);assert.match(sharedOne.share.code,SHARE_CODE);assert.match(sharedTwo.share.code,SHARE_CODE);assert.notEqual(sharedOne.share.code,sharedTwo.share.code);assert.equal(sharedOne.share.enabled,true);const view=f.store.shared(sharedOne.share.code);assert.equal(Object.hasOwn(view,"id"),false);assert.equal(JSON.stringify(view).includes(one.id),false);assert.equal(view.name,one.name);});

test("v74 public share contains only allowlisted metadata, sanitized theme and local asset references",t=>{const f=fixture(t),item=create(f.store),code=f.store.enableShare(item.id).share.code,view=f.store.shared(code),json=JSON.stringify(view);assert.deepEqual(Object.keys(view).sort(),["assetCount","assetReferences","colorProfile","coverAssetId","description","missingAssets","mood","name","share","style","tags","theme"].sort());assert.equal(view.assetReferences[0].url,asset(ASSET));for(const forbidden of ["runtime-data","imports/","node_modules","Authorization","Bearer ","GATEWAY_API_KEY"])assert.equal(json.includes(forbidden),false,forbidden);assert.doesNotMatch(json,/https?:\/\/|blob:|data:|file:|javascript:/iu);});

test("v74 import creates a fresh private copy and resets usage metadata",t=>{const f=fixture(t),source=create(f.store);f.store.apply(source.id);const code=f.store.enableShare(source.id).share.code,copy=f.store.importShared(code);assert.notEqual(copy.id,source.id);assert.equal(copy.name,`${source.name} (副本)`);assert.deepEqual(copy.tags,source.tags);assert.equal(copy.description,source.description);assert.equal(copy.usageCount,0);assert.equal(copy.lastUsedAt,null);assert.deepEqual(copy.share,{enabled:false,code:"",createdAt:null,expiresAt:null});assert.equal(f.store.list().length,2);});

test("v74 missing assets require explicit continuation and never download resources",t=>{const f=fixture(t),source=create(f.store),code=f.store.enableShare(source.id).share.code;f.existing.clear();const view=f.store.shared(code);assert.equal(view.missingAssets.length,1);assert.throws(()=>f.store.importShared(code),error=>error.code==="THEME_SHARE_MISSING_ASSETS"&&error.statusCode===409&&error.missingAssets.length===1);const copy=f.store.importShared(code,{allowMissingAssets:true});assert.equal(copy.coverAssetId,"");assert.equal(copy.missingAssets.length,1);assert.equal(copy.theme.assets.backgroundImage,asset(ASSET));});

test("v74 validator rejects external URLs, local paths and sensitive injected fields",t=>{const f=fixture(t);for(const value of ["http://evil.test/x","https://evil.test/x","blob:x","data:image/png,x","file:///tmp/x","/tmp/private.png","../private.png","runtime-data/theme-presets/presets.json","C:\\private\\x.png"])assert.throws(()=>f.store.create({name:"bad",theme:theme(value)}),error=>error.code==="THEME_PRESET_INVALID_FIELD"||error.code==="THEME_PRESET_ASSET_FORBIDDEN",value);for(const field of ["Authorization","token","userData","runtimePath"])assert.throws(()=>f.store.create({name:"bad",theme:{...theme(""),future:{[field]:"runtime-data/private"}}}),error=>error.code==="THEME_PRESET_INVALID_FIELD");});

test("v74 share lifecycle records minimal EventStore payloads",t=>{const f=fixture(t),item=create(f.store),shared=f.store.enableShare(item.id),code=shared.share.code;f.store.disableShare(item.id);f.store.enableShare(item.id);const secondCode=f.store.public(f.store.get(item.id)).share.code,copy=f.store.importShared(secondCode);const selected=f.events.filter(event=>event.input.eventType.startsWith("theme_preset.share")||event.input.eventType==="theme_preset.imported");assert.deepEqual(selected.map(event=>event.input.eventType),["theme_preset.shared","theme_preset.share_disabled","theme_preset.shared","theme_preset.imported"]);for(const event of selected){assert.deepEqual(Object.keys(event.input.payload).sort(),["presetId","shareCode","timestamp"]);assert.match(event.input.payload.shareCode,SHARE_CODE);assert.equal(event.context.source,"theme-preset-store");assert.equal(JSON.stringify(event).includes("theme\":\{"),false);}assert.equal(selected.at(-1).input.payload.presetId,copy.id);assert.equal(code,selected[0].input.payload.shareCode);});

test("v74 routes keep public reads open and every share write authorized",async t=>{const f=fixture(t),item=create(f.store),app=Fastify({logger:false});registerThemePresetRoutes(app,{store:f.store,apiKey:"secret"});t.after(()=>app.close());const unauthorized=await app.inject({method:"POST",url:`/api/theme/presets/${item.id}/share`});assert.equal(unauthorized.statusCode,401);const enabled=await app.inject({method:"POST",url:`/api/theme/presets/${item.id}/share`,headers:{authorization:"Bearer secret"},payload:{}});assert.equal(enabled.statusCode,200);const code=enabled.json().data.share.code,publicRead=await app.inject({method:"GET",url:`/api/theme/share/${code}`});assert.equal(publicRead.statusCode,200);assert.equal(Object.hasOwn(publicRead.json().data,"id"),false);const importUnauthorized=await app.inject({method:"POST",url:`/api/theme/share/${code}/import`,payload:{}});assert.equal(importUnauthorized.statusCode,401);const imported=await app.inject({method:"POST",url:`/api/theme/share/${code}/import`,headers:{authorization:"Bearer secret"},payload:{}});assert.equal(imported.statusCode,200);assert.notEqual(imported.json().data.id,item.id);const disabled=await app.inject({method:"DELETE",url:`/api/theme/presets/${item.id}/share`,headers:{authorization:"Bearer secret"}});assert.equal(disabled.statusCode,200);assert.equal((await app.inject({method:"GET",url:`/api/theme/share/${code}`})).statusCode,404);});

test("v74 Theme Center exposes safe share management, public preview and explicit missing-asset continuation",()=>{const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"frontend-p4b/theme-center.html"),"utf8"),js=fs.readFileSync(path.join(root,"frontend-p4b/assets/js/theme-center.js"),"utf8"),css=fs.readFileSync(path.join(root,"frontend-p4b/assets/css/theme-center.css"),"utf8"),sw=fs.readFileSync(path.join(root,"frontend-p4b/sw.js"),"utf8");for(const marker of ["生成分享码","复制分享码","关闭分享","公开主题","继续导入","取消导入","data-theme-share-preview"])assert.ok(html.includes(marker),marker);for(const marker of ["🌐 已分享","🔒 私有","缺失素材","/api/theme/share/","allowMissingAssets","navigator.clipboard.writeText","activeBefore"])assert.ok(js.includes(marker),marker);assert.doesNotMatch(js,/innerHTML\s*=/u);assert.doesNotMatch(css,/\.(?:chat-shell|chat-main|message-list|session-drawer)[^{]*\{[^}]*(?:display|position|height|overflow|z-index|transform)\s*:/u);assert.match(sw,/xinban-shell-v74-p4b/u);assert.match(sw,/BUILD_REVISION = "v74"/u);assert.match(fs.readFileSync(path.join(root,"ai-companion-frontend/game/index.html"),"utf8"),/game-v49-p4b/u);});
