"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),test=require("node:test"),Fastify=require("fastify");
const {ThemePresetStore}=require("../theme-preset-service"),{registerThemePresetRoutes}=require("../theme-preset-routes"),themes=require("../frontend-p4b/assets/js/theme-store");
const A="11111111-1111-4111-8111-111111111111",B="22222222-2222-4222-8222-222222222222",asset=id=>`/api/theme/assets/${id}`;
const theme=(id=A,color="#355f7d")=>({...themes.DEFAULT_THEME,id:`theme-${id}`,name:"fixture",tokens:{...themes.DEFAULT_THEME.tokens,colorPrimary:color},assets:{...themes.DEFAULT_THEME.assets,backgroundImage:asset(id)},customCss:""});
function fixture(t){const rootDir=fs.mkdtempSync(path.join(os.tmpdir(),"theme-center-v73-")),events=[],existing=new Set([A]);let tick=0;const clock=()=>new Date(Date.UTC(2026,7,22,10,0,tick++));t.after(()=>fs.rmSync(rootDir,{recursive:true,force:true}));const store=new ThemePresetStore({rootDir,assetStore:{list:()=>[...existing].map(id=>({id}))},eventStore:{create(input,context){events.push({input,context});}},clock});return{store,events,existing};}
const create=(store,overrides={})=>store.create({name:"雾蓝清晨",description:"安静通透的浅蓝主题",tags:["清晨","蓝色"],mood:"平静",style:"玻璃",colorProfile:"冷色",theme:theme(),...overrides});

test("v73 library lists complete cards and filters searchable metadata",t=>{const f=fixture(t),first=create(f.store),second=create(f.store,{name:"暖阳午后",description:"温暖明亮",tags:["暖色"],mood:"开心",style:"柔和",colorProfile:"橙色",theme:theme(A,"#a86632")});f.store.update(second.id,{favorite:true});f.store.apply(first.id);const all=f.store.library({sort:"name",limit:1});assert.equal(all.items.length,1);assert.equal(all.total,2);assert.equal(all.nextCursor,"1");for(const field of ["coverAssetId","name","description","tags","mood","style","colorProfile","createdAt","updatedAt","lastUsedAt","usageCount","favorite"])assert.ok(Object.hasOwn(f.store.public(f.store.get(first.id)),field),field);assert.deepEqual(f.store.library({query:"平静"}).items.map(item=>item.id),[first.id]);assert.deepEqual(f.store.library({query:"玻璃"}).items.map(item=>item.id),[first.id]);assert.deepEqual(f.store.library({query:"冷色"}).items.map(item=>item.id),[first.id]);assert.deepEqual(f.store.library({tag:"暖色"}).items.map(item=>item.id),[second.id]);assert.deepEqual(f.store.library({favorite:true}).items.map(item=>item.id),[second.id]);assert.equal(f.store.library({sort:"recent"}).items[0].id,first.id);});

test("v73 favorite persists and records only preset id and timestamp",t=>{const f=fixture(t),item=create(f.store),updated=f.store.update(item.id,{favorite:true});assert.equal(updated.favorite,true);assert.equal(f.store.list()[0].favorite,true);const event=f.events.at(-1);assert.equal(event.input.eventType,"theme_preset.favorite_changed");assert.deepEqual(event.input.payload,{presetId:item.id,timestamp:"2026-08-22T10:00:03.000Z"});assert.equal(event.context.source,"theme-preset-store");assert.equal(JSON.stringify(event).includes("tokens"),false);});

test("v73 preview is isolated and only apply increments usage and changes active theme",t=>{const f=fixture(t),item=create(f.store),values=new Map([[themes.ACTIVE_KEY,JSON.stringify(themes.DEFAULT_THEME)]]),storage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value))},root={style:{setProperty(){},removeProperty(){}},dataset:{},classList:{add(){},remove(){}}},documentRef={documentElement:root,body:null,head:{append(){}},getElementById(){return null;},createElement(){return{};},addEventListener(){}},client=new themes.ThemeStore({storage,documentRef}),before=values.get(themes.ACTIVE_KEY),preview=f.store.previewApply(item.id);assert.equal(values.get(themes.ACTIVE_KEY),before);assert.equal(f.store.get(item.id).usageCount,0);client.applyTheme(preview.draft);assert.notEqual(values.get(themes.ACTIVE_KEY),before);assert.equal(f.store.get(item.id).usageCount,0);const applied=f.store.apply(item.id);client.applyTheme(applied.draft);assert.equal(applied.usageCount,1);assert.equal(f.store.get(item.id).usageCount,1);assert.ok(f.store.get(item.id).lastUsedAt);f.store.previewApply(item.id);assert.equal(f.store.get(item.id).usageCount,1);f.store.apply(item.id);assert.equal(f.store.get(item.id).usageCount,2);});

test("v73 cover asset accepts only existing local asset ids",t=>{const f=fixture(t);assert.equal(create(f.store,{coverAssetId:A}).coverAssetId,A);assert.throws(()=>create(f.store,{name:"missing",coverAssetId:B}),error=>error.code==="THEME_PRESET_COVER_ASSET_NOT_FOUND");for(const value of ["https://example.com/a.png","data:image/png;base64,AA==","blob:local","file:///tmp/a","javascript:alert(1)"])assert.throws(()=>create(f.store,{name:`bad-${value.length}`,coverAssetId:value}),error=>error.code==="THEME_PRESET_INVALID"||error.code==="THEME_PRESET_ASSET_FORBIDDEN");});

test("v73 validator keeps dangerous fields and protocols rejected",t=>{const f=fixture(t);for(const field of ["selector","css","style","script","html","iframe","href","src"])assert.throws(()=>create(f.store,{name:`bad-${field}`,theme:{...theme(),future:{[field]:"x"}}}),error=>error.code==="THEME_PRESET_INVALID_FIELD");for(const protocol of ["http://x","https://x","data:text/plain,x","blob:x","file:///x","javascript:alert(1)"])assert.throws(()=>create(f.store,{name:"bad protocol",theme:{...theme(),future:{value:protocol}}}),error=>error.code==="THEME_PRESET_INVALID_FIELD");});

test("v73 library route exposes authenticated pagination and favorite query",async t=>{const f=fixture(t),one=create(f.store),two=create(f.store,{name:"收藏主题"});f.store.update(two.id,{favorite:true});const app=Fastify({logger:false});registerThemePresetRoutes(app,{store:f.store,apiKey:"test"});t.after(()=>app.close());const response=await app.inject({method:"GET",url:"/api/theme/presets/library?favorite=true&limit=1&sort=popular",headers:{authorization:"Bearer test"}});assert.equal(response.statusCode,200);assert.deepEqual(Object.keys(response.json().data).sort(),["items","nextCursor","total"]);assert.equal(response.json().data.total,1);assert.equal(response.json().data.items[0].id,two.id);assert.notEqual(one.id,two.id);});

test("v73 Theme Center UI has safe covers, filters, four isolated previews and no protected chat layout edits",()=>{const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"frontend-p4b/theme-center.html"),"utf8"),js=fs.readFileSync(path.join(root,"frontend-p4b/assets/js/theme-center.js"),"utf8"),css=fs.readFileSync(path.join(root,"frontend-p4b/assets/css/theme-center.css"),"utf8"),settings=fs.readFileSync(path.join(root,"frontend-p4b/settings.html"),"utf8"),sw=fs.readFileSync(path.join(root,"frontend-p4b/sw.js"),"utf8");for(const text of ["全部主题","我的主题","收藏主题","最近使用","标签筛选","搜索主题","预览","应用主题","首页","聊天","空间","议事厅"])assert.ok(html.includes(text),text);for(const field of ["name","description","tags","mood","style","colorProfile","createdAt","updatedAt","lastUsedAt","usageCount"])assert.ok(js.includes(`item.${field}`),field);assert.match(js,/apply-preview/u);assert.match(js,/activeBefore/u);assert.match(js,/localCover/u);assert.doesNotMatch(js,/https?:.*(?:src|cover)|data:image|blob:|file:/iu);assert.doesNotMatch(css,/\.(?:chat-shell|chat-main|message-list|session-drawer)[^{]*\{[^}]*(?:display|position|height|overflow|z-index|transform)\s*:/u);assert.match(settings,/href="theme-center\.html"/u);assert.match(sw,/xinban-shell-v75-p4b/u);assert.match(sw,/theme-center\.html/u);assert.match(fs.readFileSync(path.join(root,"ai-companion-frontend/game/index.html"),"utf8"),/game-v49-p4b/u);});
