"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const themes = require("../frontend-p4b/assets/js/theme-store.js");

const root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8");
const local="/api/theme/assets/11111111-1111-4111-8111-111111111111";
const region={enabled:true,backgroundColor:"rgba(91,167,232,.24)",textColor:"#243244",borderColor:"rgba(91,167,232,.4)",accentColor:"#1d4f73",borderWidth:2,radius:24,shadow:.18,blur:12,opacity:.8,glassOpacity:.7,image:{enabled:true,url:local,opacity:.25,size:"contain",position:"right",repeat:"no-repeat",blendMode:"soft-light",offsetX:12,offsetY:-8,scale:1.4,blur:3}};

test("v66 advanced editor entry, pages, regions, previews and actions exist",()=>{const html=read("frontend-p4b/theme-workshop.html");for(const text of ["高级美化编辑器","聊天预览","小窝预览","通用页面预览","保存草稿","应用到当前主题","另存为新主题","只保留颜色","关闭所有图片"])assert.ok(html.includes(text),text);for(const page of ["chat","home","settings","collaboration","space"])assert.ok(Object.keys(themes.DESIGN_REGIONS).some(key=>key.startsWith(`${page}.`)),page);for(const key of ["home.hero","home.todayCard","home.progress","home.startChatCard","home.secondaryCards","home.activeButton","chat.activeButton"])assert.ok(themes.DESIGN_REGIONS[key],key);});

test("v66 customDesign validates fields and rejects selectors, layout properties and external images",()=>{const design=themes.normalizeCustomDesign({version:99,selector:"body",regions:{"chat.header":{...region,display:"none",position:"fixed",height:"100vh",overflow:"hidden",zIndex:9999,transform:"scale(9)",image:{...region.image,url:"https://evil.test/x.png"}},"evil.selector":region}});assert.equal(design.version,1);assert.equal(design.selector,undefined);assert.equal(design.regions["evil.selector"],undefined);for(const field of ["display","position","height","overflow","zIndex","transform"])assert.equal(design.regions["chat.header"][field],undefined,field);assert.equal(design.regions["chat.header"].image.url,"");});

test("v66 local material and alpha appearance round-trip through exported theme JSON",()=>{const theme=themes.normalizeTheme({...themes.DEFAULT_THEME,id:"v66-custom",source:"custom",assetLibrary:[{id:"asset",kind:"backgroundImage",url:local}],customDesign:{version:1,regions:{"home.hero":region}}});const store=new themes.ThemeStore({storage:null,documentRef:null}),pack=JSON.parse(JSON.stringify(store.exportTheme(theme))),roundTrip=themes.normalizeTheme(pack.theme);assert.deepEqual(roundTrip.customDesign.regions["home.hero"],theme.customDesign.regions["home.hero"]);assert.equal(roundTrip.customDesign.regions["home.hero"].backgroundColor,"rgba(91,167,232,.24)");assert.equal(roundTrip.customDesign.regions["home.hero"].image.url,local);});

test("v66 CSS variables cover pain-point regions and apply only after explicit enable",()=>{const disabled=themes.cssVariables(themes.DEFAULT_THEME);assert.equal(disabled["--xb-design-home-hero-bg"],"");const variables=themes.cssVariables({...themes.DEFAULT_THEME,customDesign:{version:1,regions:{"home.hero":region,"home.startChatCard":region,"home.progress":region,"home.iconBlock":region,"home.activeButton":region,"chat.activeButton":region}}});for(const name of ["--xb-design-home-hero-bg","--xb-design-home-start-chat-card-bg","--xb-design-home-icon-block-bg","--xb-design-home-active-button-bg","--xb-design-chat-active-button-bg"])assert.equal(variables[name],region.backgroundColor,name);assert.equal(variables["--xb-design-home-progress-accent"],region.accentColor);});

test("v66 draft does not write activeTheme while applyTheme does",()=>{const values=new Map(),storage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value))},rootNode={style:{setProperty(){},removeProperty(){}},dataset:{},classList:{add(){},remove(){}}},documentRef={documentElement:null,body:null,head:{append(){}},getElementById(){return null;},createElement(){return{};}};documentRef.documentElement=rootNode;const js=read("frontend-p4b/assets/js/theme-workshop.js");assert.match(js,/xinban-theme-design-draft-v1/u);assert.match(js,/localStorage\.setItem\(DESIGN_DRAFT_KEY/u);const store=new themes.ThemeStore({storage,documentRef}),theme={...themes.DEFAULT_THEME,customDesign:{version:1,regions:{"chat.header":region}}};storage.setItem("xinban-theme-design-draft-v1",JSON.stringify(theme.customDesign));assert.equal(values.has(themes.ACTIVE_KEY),false);store.applyTheme(theme);assert.equal(JSON.parse(values.get(themes.ACTIVE_KEY)).customDesign.regions["chat.header"].enabled,true);});

test("v66 fixed CSS has no arbitrary selector input or chat main-layout mutation",()=>{const css=read("frontend-p4b/assets/css/theme.css"),js=read("frontend-p4b/assets/js/theme-workshop.js"),section=css.slice(css.indexOf("v66 fixed-region"));assert.match(section,/--xb-design-home-hero-bg/u);assert.match(section,/--xb-design-chat-active-button-bg/u);assert.doesNotMatch(js,/customDesign[\s\S]{0,80}(?:selector|cssText|insertRule)/u);for(const selector of [".chat-shell",".chat-main",".message-list",".session-drawer"]){const rules=[...section.matchAll(new RegExp(`${selector.replace(".","\\.")}[^{}]*\\{([^}]*)\\}`,"gu"))].map(match=>match[1]).join(";");assert.doesNotMatch(rules,/(?:display|position|height|overflow|z-index|transform)\s*:/u,selector);}assert.doesNotMatch(section,/gomoku|game-board|canvas/u);});

test("v66 version markers advance while game build stays v49",()=>{const common=read("frontend-p4b/assets/js/common.js"),sw=read("frontend-p4b/sw.js"),game=read("ai-companion-frontend/game/index.html");assert.match(common,/v67-p4b/u);assert.match(common,/p4b-sw-controller-refresh-v67/u);assert.match(sw,/xinban-shell-v67-p4b/u);assert.match(sw,/v67-p4b-live-visual-editor/u);assert.match(game,/game-v49-p4b/u);});
