"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const Fastify = require("fastify");
const multipart = require("@fastify/multipart");
const { test } = require("node:test");
const { registerThemeAssetRoutes } = require("../theme-asset-routes");
const { ThemeAssetStore } = require("../theme-asset-service");

function png(width=2,height=2){const b=Buffer.alloc(45);Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]).copy(b);b.writeUInt32BE(13,8);b.write("IHDR",12,"ascii");b.writeUInt32BE(width,16);b.writeUInt32BE(height,20);b[24]=8;b[25]=6;b.writeUInt32BE(0,33);b.write("IEND",37,"ascii");return b;}
function jpeg(width=2,height=2){return Buffer.from([0xff,0xd8,0xff,0xc0,0x00,0x0b,0x08,height>>8,height&255,width>>8,width&255,0x01,0x01,0x11,0x00,0xff,0xd9]);}
function webp(width=2,height=2){const b=Buffer.alloc(30);b.write("RIFF",0);b.writeUInt32LE(22,4);b.write("WEBPVP8X",8);b.writeUInt32LE(10,16);b.writeUIntLE(width-1,24,3);b.writeUIntLE(height-1,27,3);return b;}
function body(file,{filename="asset.png",mime="image/png",field="file"}={}){const boundary="----xinban-v69";return{payload:Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="${field}"; filename="${filename}"\r\nContent-Type: ${mime}\r\n\r\n`),file,Buffer.from(`\r\n--${boundary}--\r\n`)]),headers:{"content-type":`multipart/form-data; boundary=${boundary}`,authorization:"Bearer test-key"}};}
async function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),"theme-v69-")),events=[],store=new ThemeAssetStore({rootDir:path.join(root,"theme-assets"),eventStore:{create(input,context){events.push({input,context});}}}),app=Fastify({logger:false});await app.register(multipart);registerThemeAssetRoutes(app,{apiKey:"test-key",store,localizer:{localize:async()=>({localized:[],failed:[]})},previewService:{preview:async()=>({items:[],failed:[]})},previewStore:store});await app.ready();t.after(async()=>{await app.close();fs.rmSync(root,{recursive:true,force:true});});return{root,store,app,events};}

test("v69 uploads PNG JPEG and WebP with safe metadata and permissions",async t=>{const f=await fixture(t);for(const [file,mime,name] of [[png(),"image/png","spring.png"],[jpeg(),"image/jpeg","photo.jpg"],[webp(),"image/webp","card.webp"]]){const part=body(file,{filename:name,mime}),r=await f.app.inject({method:"POST",url:"/api/theme/assets/upload",payload:part.payload,headers:part.headers});assert.equal(r.statusCode,200,r.body);const item=r.json().data;assert.match(item.id,/^[0-9a-f-]{36}$/u);assert.equal(item.source,"upload");assert.equal(item.mime,mime);assert.equal(item.width,2);assert.equal(item.height,2);assert.doesNotMatch(item.id,/spring|photo|card/u);const resolved=f.store.resolve(item.id);assert.equal(fs.statSync(resolved.filename).mode&0o777,0o600);}assert.equal(fs.statSync(f.store.rootDir).mode&0o777,0o700);assert.equal(f.events.length,3);assert.ok(f.events.every(x=>x.input.eventType==="theme_asset.uploaded"&&x.context.source==="theme-asset-store"));});

test("v69 upload rejects unsupported, disguised, mismatched, corrupted, oversized, unsafe dimensions and traversal",async t=>{const f=await fixture(t);const cases=[[Buffer.from("<svg/>"),"image/svg+xml","a.svg",415],[Buffer.from("<html>"),"text/html","a.html",415],[Buffer.from("plain text"),"image/png","a.png",415],[png(),"image/jpeg","a.jpg",415],[png().subarray(0,32),"image/png","broken.png",415],[Buffer.alloc(2*1024*1024+1),"image/png","large.png",413],[png(8193,1),"image/png","wide.png",413],[png(8000,5000),"image/png","pixels.png",413]];for(const [file,mime,filename,status] of cases){const part=body(file,{mime,filename}),r=await f.app.inject({method:"POST",url:"/api/theme/assets/upload",payload:part.payload,headers:part.headers});assert.equal(r.statusCode,status,`${filename}: ${r.body}`);}assert.throws(()=>f.store.upload(png(),{mimeType:"image/png",filename:"../escape.png"}),error=>error.code==="THEME_ASSET_FILENAME_INVALID");});

test("v69 asset mutation and library routes require bearer authorization",async t=>{const f=await fixture(t);for(const request of [{method:"POST",url:"/api/theme/assets/upload"},{method:"GET",url:"/api/theme/assets/library"},{method:"PATCH",url:"/api/theme/assets/11111111-1111-4111-8111-111111111111",payload:{}},{method:"DELETE",url:"/api/theme/assets/11111111-1111-4111-8111-111111111111"}])assert.equal((await f.app.inject(request)).statusCode,401);});

test("v69 library includes uploaded, localized, and historical assets without secrets or paths",async t=>{const f=await fixture(t),uploaded=f.store.upload(png(),{mimeType:"image/png",filename:"green.png",category:"background"}),localized=f.store.save(png(),"image/png",{source:"localized",category:"bubble"});const legacyId="11111111-1111-4111-8111-111111111111";fs.writeFileSync(path.join(f.store.rootDir,`${legacyId}.png`),png(),{mode:0o600});const r=await f.app.inject({method:"GET",url:"/api/theme/assets/library",headers:{authorization:"Bearer test-key"}});assert.equal(r.statusCode,200);const items=r.json().data.items;assert.ok(items.some(x=>x.id===uploaded.id&&x.source==="upload"));assert.ok(items.some(x=>x.id===localized.id&&x.source==="localized"));assert.ok(items.some(x=>x.id===legacyId&&x.source==="history"&&x.label==="未命名素材"));assert.doesNotMatch(JSON.stringify(items),/runtime-data|authorization|bearer|token|sourceUrl/iu);});

test("v69 metadata whitelist and soft delete preserve safe lifecycle",async t=>{const f=await fixture(t),asset=f.store.upload(png(),{mimeType:"image/png",filename:"safe.png"}),auth={authorization:"Bearer test-key"};let r=await f.app.inject({method:"PATCH",url:asset.url,headers:{...auth,"content-type":"application/json"},payload:{label:"浅绿聊天背景",category:"background"}});assert.equal(r.statusCode,200);assert.equal(r.json().data.label,"浅绿聊天背景");assert.equal(r.json().data.category,"background");for(const payload of [{path:"/tmp/x"},{category:"unknown"},{label:"<b>bad</b>"}])assert.equal((await f.app.inject({method:"PATCH",url:asset.url,headers:{...auth,"content-type":"application/json"},payload})).statusCode,400);r=await f.app.inject({method:"DELETE",url:asset.url,headers:auth});assert.equal(r.statusCode,200);assert.equal((await f.app.inject({method:"GET",url:asset.url})).statusCode,404);assert.equal((await f.app.inject({method:"GET",url:"/api/theme/assets/library",headers:auth})).json().data.items.some(x=>x.id===asset.id),false);assert.ok(fs.readdirSync(f.store.trashDir).some(name=>name.startsWith(asset.id)));assert.equal(fs.statSync(f.store.trashDir).mode&0o777,0o700);assert.equal((await f.app.inject({method:"DELETE",url:"/api/theme/assets/..%2Fetc%2Fpasswd",headers:auth})).statusCode>=400,true);assert.ok(f.events.some(x=>x.input.eventType==="theme_asset.renamed"));assert.ok(f.events.some(x=>x.input.eventType==="theme_asset.deleted"));});
