"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),test=require("node:test"),Fastify=require("fastify");
const {ThemePresetStore}=require("../theme-preset-service"),{registerThemePresetRoutes}=require("../theme-preset-routes"),themes=require("../frontend-p4b/assets/js/theme-store"),studio=require("../frontend-p4b/assets/js/theme-studio-v76");
const ASSET="11111111-1111-4111-8111-111111111111",asset=`/api/theme/assets/${ASSET}`;
const theme=(color="#76549f")=>({...themes.DEFAULT_THEME,name:"studio fixture",tokens:{...themes.DEFAULT_THEME.tokens,colorPrimary:color},assets:{...themes.DEFAULT_THEME.assets,backgroundImage:asset},customCss:""});
function fixture(t){const rootDir=fs.mkdtempSync(path.join(os.tmpdir(),"theme-studio-v76-")),events=[];let tick=0;const clock=()=>new Date(Date.UTC(2026,7,25,10,0,tick++));t.after(()=>fs.rmSync(rootDir,{recursive:true,force:true}));return{store:new ThemePresetStore({rootDir,assetStore:{list:()=>[{id:ASSET}]},eventStore:{create(input,context){events.push({input,context});}},clock}),events};}
const create=store=>store.create({name:"Studio 主题",coverAssetId:ASSET,theme:theme()});

test("v76 creates manual versions and caps each preset at 30",t=>{const f=fixture(t),item=create(f.store);for(let index=0;index<32;index+=1){f.store.update(item.id,{theme:theme(`#${index.toString(16).padStart(6,"0")}`)});f.store.createVersion(item.id,{name:`版本 ${index}`});}const versions=f.store.versions(item.id);assert.equal(versions.length,30);assert.equal(versions[0].name,"版本 31");assert.equal(versions.at(-1).name,"版本 2");assert.equal(f.store.public(f.store.get(item.id)).versionCount,30);assert.equal(Object.hasOwn(f.store.public(f.store.get(item.id)),"versions"),false);});

test("v76 apply auto-saves a version while restore changes only preset draft",t=>{const f=fixture(t),item=create(f.store),activeTheme=theme("#112233"),usageBefore=item.usageCount,applied=f.store.apply(item.id);assert.equal(applied.usageCount,usageBefore+1);assert.ok(applied.versionId);f.store.update(item.id,{theme:theme("#abcdef")});const beforeRestore=f.store.get(item.id),restored=f.store.restoreVersion(item.id,applied.versionId),after=f.store.get(item.id);assert.equal(restored.draft.tokens.colorPrimary,item.theme.tokens.colorPrimary);assert.equal(after.theme.tokens.colorPrimary,"#abcdef");assert.equal(after.updatedAt,beforeRestore.updatedAt);assert.equal(after.usageCount,beforeRestore.usageCount);assert.deepEqual(activeTheme,theme("#112233"));});

test("v76 version snapshots pass the preset validator again on read and restore",t=>{const f=fixture(t),item=create(f.store),version=f.store.createVersion(item.id),items=f.store.read();items[0].versions[0].snapshot.assets.backgroundImage="https://evil.test/theme.png";f.store.write(items);assert.throws(()=>f.store.versions(item.id),error=>error.code==="THEME_PRESET_INVALID_FIELD"||error.code==="THEME_PRESET_ASSET_FORBIDDEN");assert.throws(()=>f.store.restoreVersion(item.id,version.id),error=>error.code==="THEME_PRESET_INVALID_FIELD"||error.code==="THEME_PRESET_ASSET_FORBIDDEN");});

test("v76 version EventStore payloads are minimal",t=>{const f=fixture(t),item=create(f.store),version=f.store.createVersion(item.id,{name:"安全快照"});f.store.restoreVersion(item.id,version.id);const selected=f.events.filter(event=>event.input.eventType.startsWith("theme_preset.version_"));assert.deepEqual(selected.map(event=>event.input.eventType),["theme_preset.version_created","theme_preset.version_restored"]);for(const event of selected){assert.deepEqual(Object.keys(event.input.payload).sort(),["presetId","timestamp","versionId"]);assert.equal(event.input.payload.presetId,item.id);assert.equal(event.input.payload.versionId,version.id);assert.equal(event.context.source,"theme-preset-store");assert.equal(JSON.stringify(event).includes("snapshot"),false);}});

test("v76 authenticated version routes create, list and restore drafts",async t=>{const f=fixture(t),item=create(f.store),app=Fastify({logger:false}),auth={authorization:"Bearer secret"};registerThemePresetRoutes(app,{store:f.store,apiKey:"secret"});t.after(()=>app.close());assert.equal((await app.inject({method:"GET",url:`/api/theme/presets/${item.id}/versions`})).statusCode,401);const created=await app.inject({method:"POST",url:`/api/theme/presets/${item.id}/versions`,headers:auth,payload:{name:"路由版本"}});assert.equal(created.statusCode,200);const versionId=created.json().data.id,list=await app.inject({method:"GET",url:`/api/theme/presets/${item.id}/versions`,headers:auth});assert.equal(list.json().data.items[0].id,versionId);const restored=await app.inject({method:"POST",url:`/api/theme/presets/${item.id}/versions/${versionId}/restore`,headers:auth});assert.equal(restored.statusCode,200);assert.match(restored.json().data.draft.id,/^preset_draft_/u);});

test("v76 compare, templates, color extraction and component mapping are draft-only",()=>{const active=theme("#111111"),draft=theme("#eeeeee"),before=JSON.stringify(active),comparison=studio.compareSnapshot(active,draft);assert.equal(comparison.isolated,true);assert.equal(comparison.usageDelta,0);comparison.draft.tokens.colorPrimary="#000000";assert.equal(JSON.stringify(active),before);assert.deepEqual(Object.keys(studio.TEMPLATE_COLORS),["Glass Ocean","Night Purple","Clean White","Cyber Neon","Soft Pink"]);const generated=studio.templateDraft("Cyber Neon",draft);assert.equal(generated.name,"Cyber Neon");assert.equal(draft.name,"studio fixture");assert.deepEqual(Object.keys(studio.COMPONENT_GROUPS),["首页","聊天","空间"]);assert.ok(studio.COMPONENT_GROUPS["聊天"].some(([,key])=>key==="chat.userBubble"));const pixels=[8,16,24,255,240,32,64,255,32,220,160,255,250,220,20,255];assert.deepEqual(Object.keys(studio.extractPaletteFromPixels(pixels)),["primary","secondary","background","accent"]);});

test("v76 Studio UI keeps protected layouts, game build and activeTheme isolation",()=>{const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"frontend-p4b/theme-workshop.html"),"utf8"),js=fs.readFileSync(path.join(root,"frontend-p4b/assets/js/theme-studio-v76.js"),"utf8"),css=fs.readFileSync(path.join(root,"frontend-p4b/assets/css/theme-studio-v76.css"),"utf8"),sw=fs.readFileSync(path.join(root,"frontend-p4b/sw.js"),"utf8");for(const marker of ["版本历史","实时对比","组件","从封面提取颜色","activeTheme 隔离"])assert.ok(html.includes(marker),marker);for(const marker of ["Glass Ocean","/versions","恢复到草稿","COMPONENT_GROUPS","extractPaletteFromPixels","usageDelta:0","resolveGatewayUrl(path","crossOrigin=\"anonymous\""])assert.ok(js.includes(marker),marker);assert.doesNotMatch(js,/applyTheme\s*\(/u);assert.doesNotMatch(js,/localStorage\.(?:setItem|removeItem)/u);assert.doesNotMatch(css,/\.(?:chat-shell|chat-main|message-list|session-drawer)[^{]*\{[^}]*(?:display|position|height|overflow|z-index|transform)\s*:/u);assert.match(sw,/xinban-shell-v76-p4b/u);assert.match(fs.readFileSync(path.join(root,"ai-companion-frontend/game/index.html"),"utf8"),/game-v49-p4b/u);});
