"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),test=require("node:test"),Fastify=require("fastify");
const {ThemePresetStore}=require("../theme-preset-service"),{registerThemePresetRoutes}=require("../theme-preset-routes"),{registerThemeAssetRoutes}=require("../theme-asset-routes"),themes=require("../frontend-p4b/assets/js/theme-store");
const ASSET="11111111-1111-4111-8111-111111111111",asset=`/api/theme/assets/${ASSET}`;
const theme=(color="#76549f")=>({...themes.DEFAULT_THEME,name:"community fixture",tokens:{...themes.DEFAULT_THEME.tokens,colorPrimary:color},assets:{...themes.DEFAULT_THEME.assets,backgroundImage:asset},customCss:""});
function fixture(t){const rootDir=fs.mkdtempSync(path.join(os.tmpdir(),"theme-community-v75-")),events=[],existing=new Set([ASSET]);let tick=0;const clock=()=>new Date(Date.UTC(2026,7,24,10,0,tick++));t.after(()=>fs.rmSync(rootDir,{recursive:true,force:true}));const store=new ThemePresetStore({rootDir,assetStore:{list:()=>[...existing].map(id=>({id}))},eventStore:{create(input,context){events.push({input,context});}},clock});return{store,events,existing};}
const create=(store,overrides={})=>store.create({name:"月光社区",description:"公开主题描述",tags:["月光","玻璃"],coverAssetId:ASSET,mood:"宁静",style:"glass",colorProfile:"冷色",theme:theme(),...overrides});

test("v75 presets default private and publishing lifecycle is explicit",t=>{const f=fixture(t),item=create(f.store);assert.equal(item.visibility,"private");assert.equal(f.store.community().total,0);const published=f.store.update(item.id,{visibility:"public"});assert.equal(published.visibility,"public");assert.equal(f.store.community().total,1);const hidden=f.store.update(item.id,{visibility:"private"});assert.equal(hidden.visibility,"private");assert.equal(f.store.community().total,0);assert.deepEqual(f.events.filter(e=>/published|unpublished/u.test(e.input.eventType)).map(e=>e.input.eventType),["theme_preset.published","theme_preset.unpublished"]);});

test("v75 community list searches metadata, filters tags, paginates and sorts",t=>{const f=fixture(t),latest=create(f.store,{name:"暖阳",description:"明亮柔和",tags:["暖色"],mood:"开心",style:"soft",colorProfile:"橙色",theme:theme("#d77a42")}),popular=create(f.store,{name:"月光",visibility:"public"}),used=create(f.store,{name:"森林",tags:["自然"],visibility:"public",theme:theme("#3f805d")});f.store.update(latest.id,{visibility:"public"});f.store.favoriteCommunity(popular.id,true);f.store.communityDetail(popular.id);f.store.apply(used.id);f.store.apply(used.id);assert.deepEqual(f.store.community({query:"明亮"}).items.map(x=>x.id),[latest.id]);assert.deepEqual(f.store.community({query:"soft"}).items.map(x=>x.id),[latest.id]);assert.deepEqual(f.store.community({tag:"自然"}).items.map(x=>x.id),[used.id]);assert.equal(f.store.community({sort:"popular"}).items[0].id,popular.id);assert.equal(f.store.community({sort:"mostUsed"}).items[0].id,used.id);const page=f.store.community({sort:"latest",limit:1});assert.equal(page.items.length,1);assert.equal(page.total,3);assert.equal(page.nextCursor,"1");});

test("v75 detail alone increments viewCount while preview data and list do not",t=>{const f=fixture(t),item=create(f.store,{visibility:"public"});assert.equal(f.store.community().items[0].viewCount,0);const preview=f.store.community().items[0];assert.equal(preview.viewCount,0);assert.equal(f.store.communityDetail(item.id).viewCount,1);assert.equal(f.store.communityDetail(item.id).viewCount,2);assert.equal(f.store.public(f.store.get(item.id)).viewCount,2);});

test("v75 community copy creates a fresh private preset with reset metadata",t=>{const f=fixture(t),source=create(f.store,{visibility:"public"});f.store.apply(source.id);f.store.enableShare(source.id);f.store.favoriteCommunity(source.id,true);f.store.communityDetail(source.id);const copy=f.store.copyCommunity(source.id),raw=f.store.get(copy.id);assert.notEqual(copy.id,source.id);assert.equal(copy.name,`${source.name} (副本)`);assert.equal(copy.visibility,"private");assert.equal(copy.usageCount,0);assert.equal(copy.lastUsedAt,null);assert.equal(copy.favoriteCount,0);assert.equal(copy.viewCount,0);assert.equal(copy.communityFavorite,false);assert.equal(raw.share,null);assert.deepEqual(copy.tags,source.tags);assert.equal(copy.theme.assets.backgroundImage,asset);});

test("v75 community favorite is separate from preset favorite and records minimal event",t=>{const f=fixture(t),item=create(f.store,{visibility:"public"}),fav=f.store.favoriteCommunity(item.id,true);assert.equal(fav.communityFavorite,true);assert.equal(fav.favoriteCount,1);assert.equal(f.store.public(f.store.get(item.id)).favorite,false);assert.equal(f.store.favoriteCommunity(item.id,true).favoriteCount,1);assert.equal(f.store.favoriteCommunity(item.id,false).favoriteCount,0);const event=f.events.find(e=>e.input.eventType==="theme_preset.community_favorited");assert.deepEqual(Object.keys(event.input.payload).sort(),["presetId","timestamp"]);assert.equal(event.input.payload.presetId,item.id);assert.equal(JSON.stringify(event).includes("theme\":\{"),false);});

test("v75 public output is allowlisted, safe and keeps public asset deletion protection",async t=>{const f=fixture(t),item=create(f.store,{visibility:"public"}),view=f.store.community().items[0],json=JSON.stringify(view);assert.deepEqual(Object.keys(view).sort(),["assetReferences","colorProfile","communityFavorite","coverAssetId","createdAt","description","favoriteCount","id","missingAssets","mood","name","style","tags","theme","updatedAt","usageCount","viewCount"].sort());assert.equal(view.assetReferences[0].url,asset);assert.deepEqual(f.store.findAssetReferences(ASSET),[{presetId:item.id,name:item.name}]);for(const forbidden of ["runtime-data","imports/","node_modules","Authorization","Bearer ","GATEWAY_API_KEY","shareCode","lastUsedAt"])assert.equal(json.includes(forbidden),false,forbidden);assert.doesNotMatch(json,/https?:\/\/|blob:|data:|file:|javascript:/iu);const app=Fastify({logger:false}),unused=()=>{throw new Error("protected delete reached asset store");};registerThemeAssetRoutes(app,{localizer:{localize:unused},store:{delete:unused},previewService:{preview:unused},previewStore:{resolve:unused},presetStore:f.store,apiKey:"secret"});t.after(()=>app.close());const response=await app.inject({method:"DELETE",url:`/api/theme/assets/${ASSET}`,headers:{authorization:"Bearer secret"}});assert.equal(response.statusCode,409);assert.equal(response.json().error.code,"THEME_ASSET_REFERENCED_BY_PRESET");});

test("v75 community routes expose public reads and authorize every write",async t=>{const f=fixture(t),item=create(f.store,{visibility:"public"}),app=Fastify({logger:false});registerThemePresetRoutes(app,{store:f.store,apiKey:"secret"});t.after(()=>app.close());assert.equal((await app.inject({method:"GET",url:"/api/theme/community?sort=latest"})).statusCode,200);assert.equal((await app.inject({method:"GET",url:`/api/theme/community/${item.id}`})).json().data.viewCount,1);for(const request of [{method:"POST",url:`/api/theme/community/${item.id}/copy`},{method:"POST",url:`/api/theme/community/${item.id}/favorite`},{method:"DELETE",url:`/api/theme/community/${item.id}/favorite`}])assert.equal((await app.inject(request)).statusCode,401);const auth={authorization:"Bearer secret"};assert.equal((await app.inject({method:"POST",url:`/api/theme/community/${item.id}/favorite`,headers:auth})).json().data.favoriteCount,1);const copied=await app.inject({method:"POST",url:`/api/theme/community/${item.id}/copy`,headers:auth});assert.equal(copied.statusCode,200);assert.equal(copied.json().data.visibility,"private");assert.equal((await app.inject({method:"DELETE",url:`/api/theme/community/${item.id}/favorite`,headers:auth})).statusCode,200);});

test("v75 validator rejects external and local paths before public exposure",t=>{const f=fixture(t);for(const value of ["http://evil.test/x","https://evil.test/x","blob:x","data:image/png,x","file:///tmp/x","/tmp/private.png","../private.png","runtime-data/presets.json"])assert.throws(()=>create(f.store,{name:"bad",theme:{...theme(),assets:{...theme().assets,backgroundImage:value}}}),error=>error.code==="THEME_PRESET_INVALID_FIELD"||error.code==="THEME_PRESET_ASSET_FORBIDDEN",value);assert.throws(()=>create(f.store,{visibility:"friends"}),error=>error.code==="THEME_PRESET_VISIBILITY_INVALID");});

test("v75 Community UI has public browsing, detail routing, isolated preview and protected layouts",()=>{const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"frontend-p4b/theme-community.html"),"utf8"),js=fs.readFileSync(path.join(root,"frontend-p4b/assets/js/theme-community.js"),"utf8"),css=fs.readFileSync(path.join(root,"frontend-p4b/assets/css/theme-community.css"),"utf8"),center=fs.readFileSync(path.join(root,"frontend-p4b/assets/js/theme-center.js"),"utf8"),common=fs.readFileSync(path.join(root,"frontend-p4b/assets/js/common.js"),"utf8"),sw=fs.readFileSync(path.join(root,"frontend-p4b/sw.js"),"utf8");for(const marker of ["主题广场","搜索公开主题","最新","热门","使用最多","预览","复制到我的主题"])assert.ok(html.includes(marker),marker);for(const marker of ["收藏","公开主题详情","/api/theme/community","communityFavorite","favoriteCount","viewCount","usageCount","activeBefore","history.replaceState"])assert.ok(js.includes(marker),marker);for(const marker of ["公开主题","设为私有","查看主题页","🌐 公开","🔒 私有"])assert.ok(center.includes(marker),marker);assert.match(common,/theme-community/u);assert.doesNotMatch(js,/innerHTML\s*=/u);assert.doesNotMatch(css,/\.(?:chat-shell|chat-main|message-list|session-drawer)[^{]*\{[^}]*(?:display|position|height|overflow|z-index|transform)\s*:/u);assert.match(sw,/xinban-shell-v76-p4b/u);assert.match(sw,/theme-community\.html/u);assert.match(sw,/theme-community\.css\?v=v76-p4b/u);assert.match(sw,/theme-community\.js\?v=v76-p4b/u);assert.match(fs.readFileSync(path.join(root,"ai-companion-frontend/game/index.html"),"utf8"),/game-v49-p4b/u);});
