"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const Fastify = require("fastify");
const { registerThemeAssetRoutes } = require("../theme-asset-routes");
const { registerThemePresetRoutes } = require("../theme-preset-routes");
const { ThemePresetStore } = require("../theme-preset-service");
const themes = require("../frontend-p4b/assets/js/theme-store");

const ASSET_A="11111111-1111-4111-8111-111111111111",ASSET_B="22222222-2222-4222-8222-222222222222",url=id=>`/api/theme/assets/${id}`;
const theme=assetId=>({...themes.DEFAULT_THEME,id:"v72-current",name:"V72 Current",customCss:"",assets:{...themes.DEFAULT_THEME.assets,backgroundImage:url(assetId)},visualSlots:{...themes.DEFAULT_THEME.visualSlots,enabledByUser:true,pageBackground:{...themes.DEFAULT_THEME.visualSlots.pageBackground,url:url(assetId),enabled:true}},customDesign:{version:1,regions:{"home.hero":{...themes.DESIGN_REGION_DEFAULT,enabled:true,image:{...themes.DESIGN_IMAGE_DEFAULT,url:url(assetId),enabled:true}}}}});
function fixture(t,{assets=[ASSET_A]}={}){const rootDir=fs.mkdtempSync(path.join(os.tmpdir(),"theme-presets-v72-")),events=[];t.after(()=>fs.rmSync(rootDir,{recursive:true,force:true}));const assetStore={list:()=>assets.map(id=>({id}))},eventStore={create(input,context){events.push({input,context});}};return{store:new ThemePresetStore({rootDir,assetStore,eventStore,clock:()=>new Date("2026-08-21T12:00:00.000Z")}),events};}

test("v72 creates a sanitized complete preset with empty AI metadata",t=>{const f=fixture(t),created=f.store.create({name:"夜色",description:"安静的深色主题",tags:["深色","安静"],theme:theme(ASSET_A)});assert.equal(created.name,"夜色");assert.equal(created.theme.visualSlots.pageBackground.url,url(ASSET_A));assert.equal(created.theme.customDesign.regions["home.hero"].image.url,url(ASSET_A));assert.equal(created.mood,"");assert.equal(created.style,"");assert.equal(created.colorProfile,"");assert.deepEqual(f.events[0].input.payload,{presetId:created.id,timestamp:"2026-08-21T12:00:00.000Z"});assert.equal(f.events[0].context.source,"theme-preset-store");});

test("v72 apply preview keeps active theme isolated until explicit apply",t=>{const f=fixture(t),created=f.store.create({name:"草稿隔离",theme:theme(ASSET_A)}),storage=new Map([[themes.ACTIVE_KEY,JSON.stringify(themes.DEFAULT_THEME)]]),client=new themes.ThemeStore({storage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,String(value))},documentRef:null});const preview=f.store.previewApply(created.id);assert.equal(JSON.parse(storage.get(themes.ACTIVE_KEY)).id,themes.DEFAULT_THEME.id);assert.match(preview.draft.id,/^preset_draft_/u);assert.equal(preview.changes.background,true);f.store.apply(created.id);assert.equal(f.events.at(-1).input.eventType,"theme_preset.applied");assert.equal(JSON.parse(storage.get(themes.ACTIVE_KEY)).id,themes.DEFAULT_THEME.id);assert.equal(client.getActive().id,themes.DEFAULT_THEME.id);});

test("v72 protects assets referenced by presets from deletion",async t=>{const f=fixture(t),created=f.store.create({name:"引用保护",theme:theme(ASSET_A)});assert.deepEqual(f.store.findAssetReferences(ASSET_A),[{presetId:created.id,name:"引用保护"}]);let deleted=false;const app=Fastify({logger:false});registerThemeAssetRoutes(app,{store:{delete(){deleted=true;}},presetStore:f.store,apiKey:"test",localizer:{},previewService:{},previewStore:{}});t.after(()=>app.close());const response=await app.inject({method:"DELETE",url:`/api/theme/assets/${ASSET_A}`,headers:{authorization:"Bearer test"}});assert.equal(response.statusCode,409);assert.equal(response.json().error.code,"THEME_ASSET_REFERENCED_BY_PRESET");assert.equal(deleted,false);});

test("v72 export imports metadata and references without binary or paths",t=>{const f=fixture(t),created=f.store.create({name:"可分享",description:"安全导出",coverAssetId:ASSET_A,theme:theme(ASSET_A)}),pack=f.store.export(created.id);assert.equal(pack.type,"xinban-theme-preset");assert.equal(pack.preset.assetReferences[0].url,url(ASSET_A));const serialized=JSON.stringify(pack);assert.doesNotMatch(serialized,/data:image|blob:|https?:|runtime-data|\.png|Bearer|apiKey|secret/iu);const imported=f.store.import(pack);assert.equal(imported.name,"可分享");assert.equal(imported.theme.assets.backgroundImage,url(ASSET_A));});

test("v72 rejects dangerous fields and protocols throughout theme input",t=>{const f=fixture(t),fields=["selector","css","style","script","javascript","html","iframe","href","src"],protocols=["http://example.com/a","https://example.com/a","data:text/plain,a","blob:local","file:///tmp/a","javascript:alert(1)"];for(const field of fields)assert.throws(()=>f.store.create({name:"危险字段",theme:{...theme(ASSET_A),customDesign:{future:{[field]:"value"}}}}),error=>error.code==="THEME_PRESET_INVALID_FIELD"&&error.error==="THEME_PRESET_INVALID_FIELD"&&error.field===`customDesign.future.${field}`);for(const value of protocols)assert.throws(()=>f.store.create({name:"危险协议",theme:{...theme(ASSET_A),futureOption:{value}}}),error=>error.code==="THEME_PRESET_INVALID_FIELD"&&error.field==="futureOption.value");assert.throws(()=>f.store.create({name:"CSS",theme:{...theme(ASSET_A),customCss:"body{display:none}"}}),error=>error.code==="THEME_PRESET_INVALID_FIELD"&&error.field==="customCss");const compatible=f.store.create({name:"未来兼容",theme:{...theme(ASSET_A),futureOption:{enabled:true,mode:"new"}}});assert.equal(compatible.name,"未来兼容");});

test("v72 create update import and apply-preview share the strict validator",t=>{const f=fixture(t),created=f.store.create({name:"统一校验",theme:theme(ASSET_A)}),dangerous={...theme(ASSET_A),futureOption:{selector:"body"}},expect=fn=>assert.throws(fn,error=>error.code==="THEME_PRESET_INVALID_FIELD"&&error.field==="futureOption.selector");expect(()=>f.store.create({name:"创建",theme:dangerous}));expect(()=>f.store.update(created.id,{theme:dangerous}));expect(()=>f.store.import({type:"xinban-theme-preset",presetVersion:1,preset:{name:"导入",theme:dangerous}}));const stored=f.store.get(created.id);stored.theme.futureOption={selector:"body"};f.store.write([stored]);expect(()=>f.store.previewApply(created.id));});

test("v72 invalid field HTTP errors expose only stable error and field",async t=>{const f=fixture(t),app=Fastify({logger:false});registerThemePresetRoutes(app,{store:f.store,apiKey:"test"});t.after(()=>app.close());const response=await app.inject({method:"POST",url:"/api/theme/presets",headers:{authorization:"Bearer test","content-type":"application/json"},payload:{name:"危险",theme:{...theme(ASSET_A),customDesign:{selector:"body"}}}});assert.equal(response.statusCode,400);assert.deepEqual(response.json(),{error:"THEME_PRESET_INVALID_FIELD",field:"customDesign.selector"});});

test("v72 reports missing assets and uses default image style only in apply draft",t=>{const f=fixture(t,{assets:[]}),created=f.store.create({name:"缺失素材",theme:theme(ASSET_B)}),stored=f.store.get(created.id),preview=f.store.previewApply(created.id);assert.equal(f.store.public(stored).missingAssets[0].assetId,ASSET_B);assert.equal(stored.theme.visualSlots.pageBackground.url,url(ASSET_B));assert.equal(preview.draft.visualSlots.pageBackground.url,"");assert.equal(preview.draft.customDesign.regions["home.hero"].image.enabled,false);assert.equal(f.store.get(created.id).theme.visualSlots.pageBackground.url,url(ASSET_B));});

test("v72 CRUD and authenticated routes expose explicit write operations",async t=>{const f=fixture(t),app=Fastify({logger:false});registerThemePresetRoutes(app,{store:f.store,apiKey:"test"});t.after(()=>app.close());const auth={authorization:"Bearer test"},json={...auth,"content-type":"application/json"},created=await app.inject({method:"POST",url:"/api/theme/presets",headers:json,payload:{name:"路由预设",theme:theme(ASSET_A)}});assert.equal(created.statusCode,200);const id=created.json().data.id;assert.equal((await app.inject({method:"PATCH",url:`/api/theme/presets/${id}`,headers:json,payload:{name:"已重命名"}})).json().data.name,"已重命名");assert.equal((await app.inject({method:"POST",url:`/api/theme/presets/${id}/copy`,headers:auth})).statusCode,200);assert.equal((await app.inject({method:"GET",url:`/api/theme/presets/${id}/export`,headers:auth})).json().data.type,"xinban-theme-preset");assert.equal((await app.inject({method:"DELETE",url:`/api/theme/presets/${id}`,headers:auth})).json().data.deleted,true);});

test("v72 UI has preset tab, search/sort, live preview, confirmation and mobile layout",()=>{const root=path.join(__dirname,".."),html=fs.readFileSync(path.join(root,"frontend-p4b/theme-workshop.html"),"utf8"),js=fs.readFileSync(path.join(root,"frontend-p4b/assets/js/theme-workshop.js"),"utf8"),css=fs.readFileSync(path.join(root,"frontend-p4b/assets/css/theme-workshop.css"),"utf8");for(const marker of ["data-workshop-tab=\"presets\"","data-preset-search","data-preset-sort","保存当前主题","data-preset-apply-confirm","部分素材不存在，将使用默认样式"])assert.ok(html.includes(marker),marker);for(const label of ["应用","编辑","复制","删除","导出"])assert.ok(js.includes(`[\"${label}\"`),label);assert.match(js,/api\.cssVariables\(theme\)/u);assert.match(js,/apply-preview/u);assert.match(css,/@media\(max-width:620px\)[\s\S]*\.theme-preset-toolbar,\.theme-preset-library\{grid-template-columns:1fr\}/u);assert.doesNotMatch(css,/\.chat-(?:shell|main)|\.message-list|\.session-drawer/u);});

test("v72 preserves game v49 and uses only minimal preset event payloads",()=>{const root=path.join(__dirname,".."),game=fs.readFileSync(path.join(root,"ai-companion-frontend/game/index.html"),"utf8"),service=fs.readFileSync(path.join(root,"theme-preset-service.js"),"utf8");assert.match(game,/game-v49-p4b/u);assert.match(service,/payload:\{presetId,\.\.\.extra,timestamp:/u);assert.doesNotMatch(service,/payload:\{[^}]*theme/iu);});
