"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{test}=require("node:test"),themes=require("../frontend-p4b/assets/js/theme-store.js");
const root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8"),js=read("frontend-p4b/assets/js/theme-workshop.js"),html=read("frontend-p4b/theme-workshop.html"),css=read("frontend-p4b/assets/css/theme-workshop.css"),asset="/api/theme/assets/11111111-1111-4111-8111-111111111111";
test("v70 reference counts cover active draft slots saved themes and deduplicate positions",()=>{const shared={customDesign:{regions:{"chat.page":{image:{url:asset}}}}},refs=themes.collectThemeAssetReferences(asset,{activeTheme:{assets:{backgroundImage:asset},customDesign:shared.customDesign},currentTheme:{visualSlots:{pageBackground:{url:asset}},customDesign:{regions:{"home.hero":{image:{url:asset}}}}},draft:shared,savedThemes:[{name:"浅蓝",customDesign:{regions:{"chat.assistantBubble":{image:{url:asset}}}}}]});assert.equal(refs.length,6);assert.equal(new Set(refs.map(x=>`${x.scope}\0${x.location}`)).size,refs.length);assert.ok(refs.some(x=>x.key==="chat.page"&&x.type==="region"));});
test("v70 library experience has favorite, selection, conservative batch delete and trash restore",()=>{for(const token of ["data-filter=\"favorite\"","data-asset-select-mode","data-asset-batch-category","data-asset-batch-delete","data-asset-trash-toggle","data-design-asset-more"])assert.match(html,new RegExp(token));assert.match(js,/favorite:\s*!asset\.favorite/u);assert.match(js,/runLimited\(selectedAssets\(\)/u);assert.match(js,/rebuildReferenceCache\(\);if\(referencesFor\(asset\)\.length\)/u);assert.match(js,/\?view=trash/u);assert.match(js,/\/restore`/u);assert.match(js,/assetVisibleLimit=48/u);assert.match(js,/img\.loading="lazy"/u);assert.match(js,/setTimeout\([\s\S]{0,120}160/u);assert.match(css,/is-reference-target|design-asset-more/u);});
test("v70 reference jump only targets current editable regions and never applies saved themes",()=>{assert.match(js,/item\.scope\.startsWith\("保存主题"\)/u);assert.match(js,/selectPreviewRegion\(item\.key\)/u);const locate=js.slice(js.indexOf("const locateReference"),js.indexOf("const showReferences"));assert.doesNotMatch(locate,/applyTheme|setCurrentWorkshopTheme|activeTheme/u);});
test("v70 search and stable sorting cover requested metadata",()=>{assert.match(js,/categoryLabels\[asset\.category\]/u);assert.match(js,/sourceLabels\[asset\.source\]/u);assert.match(js,/asset\.id\.slice\(0,8\)/u);assert.match(js,/sort==="favorite"/u);assert.match(js,/sort==="usage"/u);assert.match(js,/String\(a\.id\)\.localeCompare/u);});
test("v70 trash thumbnails use authenticated temporary blobs with bounded lifecycle",()=>{const loader=js.slice(js.indexOf("const trashThumbnailUrls"),js.indexOf("const hex"));assert.match(loader,/fetch\(url,\{headers:gatewayHeaders\(\),signal:controller\.signal\}\)/u);assert.match(loader,/response\.headers\.get\("content-type"\)/u);assert.match(loader,/URL\.createObjectURL/u);assert.match(loader,/URL\.revokeObjectURL/u);assert.match(loader,/controller\.abort\(\)/u);assert.doesNotMatch(loader,/\?token=|Authorization.*url|localStorage|ThemeStore|customDesign|visualSlots/u);assert.match(js,/releaseTrashThumbnails\(\);assetGrid\.replaceChildren/u);assert.match(js,/const restoreAsset=async asset=>\{releaseTrashThumbnails\(\)/u);});
test("v70 trash URLs cannot enter themes and restored assets return to active URLs",()=>{assert.equal(themes.safeVisualAsset("/api/theme/assets/trash/11111111-1111-4111-8111-111111111111"),"");assert.deepEqual(themes.collectThemeAssetReferences("/api/theme/assets/trash/11111111-1111-4111-8111-111111111111",{activeTheme:{}}),[]);assert.equal(themes.safeVisualAsset(asset),asset);assert.match(js,/assetView==="trash"\?restoreAsset\(asset\)/u);assert.match(js,/url:asset\.url\|\|asset\.localUrl/u);});
