"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),Fastify=require("fastify"),multipart=require("@fastify/multipart"),{test}=require("node:test"),{registerThemeAssetRoutes}=require("../theme-asset-routes"),{ThemeAssetStore}=require("../theme-asset-service");
const png=()=>Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAklEQVR4AewaftIAAAANSURBVPgBAQAEAPv/AAD/DwKqCY3XAAAAAElFTkSuQmCC","base64"),auth={authorization:"Bearer test-key"};
async function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),"theme-v71-")),events=[],clock=()=>new Date("2026-08-20T09:31:00.000Z"),store=new ThemeAssetStore({rootDir:path.join(root,"theme-assets"),eventStore:{create(input){events.push(input);}},clock}),app=Fastify({logger:false});await app.register(multipart);registerThemeAssetRoutes(app,{apiKey:"test-key",store,localizer:{localize:async()=>({})},previewService:{preview:async()=>({})},previewStore:store});await app.ready();t.after(async()=>{await app.close();fs.rmSync(root,{recursive:true,force:true});});return{app,store,events};}
test("v71 tags are normalized, persistent, bounded, and legacy-safe",async t=>{const f=await fixture(t),asset=f.store.save(png(),"image/png");let response=await f.app.inject({method:"PATCH",url:asset.url,headers:auth,payload:{tags:[" 绿色 ","绿色","清新",""]}});assert.equal(response.statusCode,200,response.body);assert.deepEqual(response.json().data.tags,["绿色","清新"]);assert.deepEqual(f.store.list()[0].tags,["绿色","清新"]);for(const tags of ["绿色",Array.from({length:21},(_,i)=>`标签${i}`),["x".repeat(25)],[{}],["<b>坏</b>"]])assert.equal((await f.app.inject({method:"PATCH",url:asset.url,headers:auth,payload:{tags}})).statusCode,400);const metadata=f.store.readMetadata();delete metadata[asset.id].tags;f.store.writeMetadata(metadata);assert.deepEqual(f.store.list()[0].tags,[]);});
test("v71 note persists as text and event contains length rather than content",async t=>{const f=await fixture(t),asset=f.store.save(png(),"image/png"),note="适合聊天页浅色背景";let response=await f.app.inject({method:"PATCH",url:asset.url,headers:auth,payload:{note}});assert.equal(response.statusCode,200);assert.equal(f.store.list()[0].note,note);assert.equal((await f.app.inject({method:"PATCH",url:asset.url,headers:auth,payload:{note:"x".repeat(301)}})).statusCode,400);assert.equal((await f.app.inject({method:"PATCH",url:asset.url,headers:auth,payload:{note:{text:"bad"}}})).statusCode,400);const event=f.events.find(item=>item.eventType==="theme_asset.note_changed");assert.deepEqual(Object.keys(event.payload).sort(),["assetId","noteLength","timestamp"]);assert.doesNotMatch(JSON.stringify(event),new RegExp(note));});
test("v71 used endpoint owns timestamp and unrelated patches do not update it",async t=>{const f=await fixture(t),asset=f.store.save(png(),"image/png");assert.equal(f.store.list()[0].lastUsedAt,null);await f.app.inject({method:"PATCH",url:asset.url,headers:auth,payload:{favorite:true}});assert.equal(f.store.list()[0].lastUsedAt,null);const response=await f.app.inject({method:"POST",url:`${asset.url}/used`,headers:auth,payload:{lastUsedAt:"2099-01-01"}});assert.equal(response.statusCode,200);assert.equal(response.json().data.lastUsedAt,"2026-08-20T09:31:00.000Z");});
test("v71 new assets hash immediately and legacy hashes scan incrementally",async t=>{const f=await fixture(t),a=f.store.save(png(),"image/png"),b=f.store.save(png(),"image/png");const expected=`sha256:${crypto.createHash("sha256").update(png()).digest("hex")}`;assert.equal(a.contentHash,expected);assert.equal(b.contentHash,expected);let metadata=f.store.readMetadata();delete metadata[a.id].contentHash;delete metadata[b.id].contentHash;f.store.writeMetadata(metadata);const response=await f.app.inject({method:"POST",url:"/api/theme/assets/duplicates/scan",headers:auth,payload:{limit:1}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().data.processed,1);assert.equal(response.json().data.remaining,1);const done=await f.store.scanDuplicateHashes({limit:24,concurrency:3});assert.equal(done.remaining,0);assert.equal(done.groups.length,1);assert.equal(done.groups[0].length,2);});
test("v71 duplicate scan enforces a hard batch ceiling of 24",async t=>{const f=await fixture(t),ids=[];for(let index=0;index<25;index++)ids.push(f.store.save(png(),"image/png").id);const metadata=f.store.readMetadata();for(const id of ids)delete metadata[id].contentHash;f.store.writeMetadata(metadata);const result=await f.store.scanDuplicateHashes({limit:999,concurrency:99});assert.equal(result.processed,24);assert.equal(result.remaining,1);});
test("v71 trash and restore preserve organization metadata",async t=>{const f=await fixture(t),asset=f.store.save(png(),"image/png");f.store.update(asset.id,{favorite:true,tags:["自然"],note:"浅色"});f.store.markUsed(asset.id);const hash=f.store.list()[0].contentHash;f.store.delete(asset.id);f.store.restore(asset.id);const restored=f.store.list()[0];assert.equal(restored.favorite,true);assert.deepEqual(restored.tags,["自然"]);assert.equal(restored.note,"浅色");assert.equal(restored.lastUsedAt,"2026-08-20T09:31:00.000Z");assert.equal(restored.contentHash,hash);});
