"use strict";

const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const {test}=require("node:test");
const {ACTIVE_KEY,DEFAULT_THEME,ThemeStore,cssVariables}=require("../frontend-p4b/assets/js/theme-store.js");
const root=path.join(__dirname,"..","frontend-p4b"); const read=file=>fs.readFileSync(path.join(root,file),"utf8");

function fixture(){const values=new Map(),variables=new Map();const storage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)};const classes={add(){},remove(){}};const documentElement={style:{setProperty:(key,value)=>variables.set(key,value),removeProperty:key=>variables.delete(key),getPropertyValue:key=>variables.get(key)||""},dataset:{},classList:classes};const documentRef={documentElement,body:{classList:classes},defaultView:{CustomEvent:class{},dispatchEvent(){}},getElementById:()=>({textContent:""}),createElement:()=>({textContent:""}),head:{append(){}}};return {storage,variables,store:new ThemeStore({storage,documentRef})};}

test("an imported Echoes theme remains selected and persists as the active theme",()=>{const f=fixture();const source={...DEFAULT_THEME,name:"淡海蓝章",tokens:{...DEFAULT_THEME.tokens,chatUserBubbleBg:"#4b91c5",chatAssistantBubbleBg:"#f7fcff"}};const imported=f.store.importTheme({type:"xinban-theme",themeVersion:1,theme:source});const applied=f.store.applyTheme(imported,{persist:true,applyBackground:true});assert.equal(applied.id,imported.id);assert.equal(f.store.getActive().name,"淡海蓝章");assert.equal(JSON.parse(f.storage.getItem(ACTIVE_KEY)).tokens.chatUserBubbleBg,"#4b91c5");assert.equal(f.variables.get("--xb-chat-user-bubble-bg"),"#4b91c5");assert.equal(f.variables.get("--xb-chat-assistant-bubble-bg"),"#f7fcff");});

test("legacy localized decorations migrate disabled until explicitly enabled",()=>{const assets={...DEFAULT_THEME.assets,userBubbleDecoration:"/api/theme/assets/11111111-1111-4111-8111-111111111111",assistantBubbleDecoration:"/api/theme/assets/22222222-2222-4222-8222-222222222222",decorativeAsset:"/api/theme/assets/33333333-3333-4333-8333-333333333333",navIcon:"/api/theme/assets/44444444-4444-4444-8444-444444444444"};const safe=cssVariables({...DEFAULT_THEME,assets});assert.equal(safe["--xb-user-bubble-decor"],"none");assert.equal(safe["--xb-assistant-bubble-decor"],"none");const enabled=cssVariables({...DEFAULT_THEME,assets,visualSlots:{enabledByUser:true,userBubbleDecor:{url:assets.userBubbleDecoration,enabled:true},assistantBubbleDecor:{url:assets.assistantBubbleDecoration,enabled:true}}});assert.match(enabled["--xb-user-bubble-decor"],/11111111/u);assert.match(enabled["--xb-assistant-bubble-decor"],/22222222/u);const performance=cssVariables({...DEFAULT_THEME,assets,layout:{...DEFAULT_THEME.layout,effectsMode:"performance"},visualSlots:{enabledByUser:true,userBubbleDecor:{url:assets.userBubbleDecoration,enabled:true}}});assert.equal(performance["--xb-user-bubble-decor"],"none");});

test("workshop explicitly selects imported drafts, names applied themes and self-checks root variables",()=>{const script=read("assets/js/theme-workshop.js"),html=read("theme-workshop.html");assert.match(script,/selectedThemeId/u);assert.match(script,/setCurrentWorkshopTheme\(importedTheme\)/u);assert.match(script,/已应用：\$\{draft\.name\}/u);assert.match(script,/--xb-chat-assistant-bubble-bg/u);assert.match(html,/data-theme-active-name/u);assert.match(html,/data-theme-preview-name/u);});

test("chat and shared panels consume canonical xb variables and reload active theme",()=>{const css=read("assets/css/theme.css"),chat=read("chat.html"),store=read("assets/js/theme-store.js");for(const variable of ["--xb-color-bg","--xb-header-bg","--xb-card-bg","--xb-composer-bg","--xb-input-bg","--xb-bottom-nav-bg","--xb-chat-user-bubble-bg","--xb-chat-assistant-bubble-bg","--xb-border-color","--xb-radius-bubble"])assert.ok(css.includes(`var(${variable})`),variable);assert.match(chat,/theme-store\.js/u);assert.match(store,/applyActiveTheme\(\)/u);assert.match(store,/addEventListener\?\.\("storage"/u);assert.match(store,/addEventListener\?\.\("pageshow"/u);});

test("v59 service worker revision changes so existing clients refresh theme assets",()=>{const sw=read("sw.js");assert.match(sw,/CACHE_NAME = "xinban-shell-v66-p4b"/u);assert.match(sw,/BUILD_REVISION = "v66-p4b-visual-theme-editor"/u);});
