"use strict";

const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const themes=require("../frontend-p4b/assets/js/theme-store.js");
const root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8"),js=read("frontend-p4b/assets/js/theme-workshop.js"),html=read("frontend-p4b/theme-workshop.html"),css=read("frontend-p4b/assets/css/theme-editor.css"),local="/api/theme/assets/11111111-1111-4111-8111-111111111111";

test("v67 range, number, select and checkbox controls update live preview on input",()=>{assert.match(js,/addEventListener\("input",\(\)=>applyDesignControl/u);assert.match(js,/renderDesignPreviewLive/u);assert.match(js,/requestAnimationFrame/u);assert.match(js,/design-value-input/u);assert.match(js,/dataset\.designMirror/u);assert.doesNotMatch(js,/applyDesignControl[\s\S]{0,120}applyTheme/u);});
test("v67 image layer consumes offset, scale, opacity, fit, repeat and blend independently",()=>{for(const value of ["region.image.offsetX","region.image.offsetY","region.image.scale","region.image.opacity","region.image.size","region.image.position","region.image.repeat","region.image.blendMode"])assert.ok(js.includes(value),value);assert.match(js,/transform=`translate\(\$\{region\.image\.offsetX\}px, \$\{region\.image\.offsetY\}px\) scale\(\$\{region\.image\.scale\}\)`/u);assert.match(css,/advanced-preview__image-layer/u);assert.match(css,/position:absolute;inset:0/u);assert.match(css,/contain:paint/u);});
test("v67 custom XY survives presets and drag switches position to custom",()=>{const design=themes.normalizeCustomDesign({regions:{"home.hero":{enabled:true,image:{enabled:true,url:local,position:"custom",offsetX:18,offsetY:-24,scale:2}}}});assert.equal(design.regions["home.hero"].image.position,"custom");assert.equal(design.regions["home.hero"].image.offsetX,18);assert.equal(design.regions["home.hero"].image.offsetY,-24);assert.equal(design.regions["home.hero"].image.scale,2);assert.match(js,/target\.image\.position="custom"/u);});
test("v67 pointer drag uses capture and updates X Y without formal DOM mutation",()=>{assert.match(js,/advanced-preview__image-layer/u);assert.match(js,/setPointerCapture/u);assert.match(js,/originX\+moveEvent\.clientX-startX/u);assert.match(js,/originY\+moveEvent\.clientY-startY/u);assert.match(js,/event\.preventDefault\(\)/u);});
test("v67 scale buttons, reset image and bounded 0.1x to 4x are present",()=>{for(const text of ["缩小","100%","放大","重置图片"])assert.ok(html.includes(text),text);assert.match(js,/Math\.max\(\.1,Math\.min\(4/u);assert.match(js,/DESIGN_IMAGE_DEFAULT/u);const small=themes.normalizeCustomDesign({regions:{"chat.userBubble":{image:{scale:0}}}}),large=themes.normalizeCustomDesign({regions:{"chat.userBubble":{image:{scale:9}}}});assert.equal(small.regions["chat.userBubble"].image.scale,.1);assert.equal(large.regions["chat.userBubble"].image.scale,4);});
test("v67 thumbnail picker only exposes safe localized assets and filters kinds",()=>{assert.match(html,/data-design-asset-picker/u);assert.match(html,/data-design-asset-grid/u);assert.match(js,/safeAssetImage\(asset\.url\)/u);assert.match(js,/design-asset-choice/u);for(const label of ["全部","背景","气泡","头像","输入栏","卡片","装饰","其他"])assert.ok(html.includes(label),label);assert.equal(themes.normalizeCustomDesign({regions:{"home.hero":{image:{enabled:true,url:"https://evil.test/x.png"}}}}).regions["home.hero"].image.url,"");});
test("v67 resolves every displayed local theme asset through the Gateway origin",()=>{const production={locationRef:{hostname:"chat.xiaowo.homes",origin:"https://chat.xiaowo.homes"}},localhost={baseUrl:"http://localhost:3000/v1"};assert.equal(themes.resolveThemeAssetUrl("/api/theme/assets/abc",production),"https://api.xiaowo.homes/api/theme/assets/abc");assert.equal(themes.resolveThemeAssetUrl("/api/theme/assets/abc",localhost),"http://localhost:3000/api/theme/assets/abc");assert.equal(themes.resolveThemeAssetUrl("https://api.xiaowo.homes/api/theme/assets/abc",production),"https://api.xiaowo.homes/api/theme/assets/abc");for(const unsafe of ["https://evil.test/api/theme/assets/abc","https://chat.xiaowo.homes/api/theme/assets/abc","data:image/png;base64,AA==","blob:https://api.xiaowo.homes/id","javascript:alert(1)","file:///api/theme/assets/abc","//api.xiaowo.homes/api/theme/assets/abc"])assert.equal(themes.resolveThemeAssetUrl(unsafe,production),"",unsafe);assert.match(js,/const imageUrl=safeAssetImage\(region\.image\.url\)/u);assert.match(js,/backgroundImage=`url\(\$\{JSON\.stringify\(imageUrl\)\}\)`/u);assert.doesNotMatch(js,/backgroundImage=`url\(\$\{JSON\.stringify\(region\.image\.url\)\}\)`/u);});
test("v67 custom design stores relative URLs while formal CSS resolves them",()=>{const design=themes.normalizeCustomDesign({regions:{"home.hero":{enabled:true,image:{enabled:true,url:local}}}});assert.equal(design.regions["home.hero"].image.url,local);const variables=themes.customDesignVariables(design,{locationRef:{hostname:"chat.xiaowo.homes",origin:"https://chat.xiaowo.homes"}});assert.equal(variables["--xb-design-home-hero-image"],`url("https://api.xiaowo.homes${local}")`);assert.equal(JSON.stringify(design).includes("api.xiaowo.homes"),false);});
test("v67 clicking preview selects region and shows outline label",()=>{assert.match(js,/closest\("\[data-design-preview-region\]"\)/u);assert.match(js,/selectPreviewRegion/u);assert.match(css,/is-design-selected/u);assert.match(css,/content:attr\(data-design-label\)/u);});
test("v67 undo redo is draft-only, bounded and coalesces pointer or slider actions",()=>{assert.match(html,/data-design-undo/u);assert.match(html,/data-design-redo/u);assert.match(js,/designHistory\.length>30/u);assert.match(js,/beginDesignHistory/u);assert.match(js,/commitDesignHistory/u);assert.match(js,/pointerdown/u);assert.match(js,/addEventListener\("change"/u);assert.doesNotMatch(js,/undoDesign[\s\S]{0,240}ACTIVE_KEY/u);});
test("v67 has four collapsible groups, safe layer and clip enums",()=>{for(const summary of ["颜色","图片","位置","外观"])assert.match(html,new RegExp(`<summary>${summary}</summary>`,"u"));for(const layer of ["background","behind","front"])assert.match(html,new RegExp(`value="${layer}"`,"u"));const design=themes.normalizeCustomDesign({regions:{"chat.header":{image:{layer:"9999",clip:false}}}});assert.equal(design.regions["chat.header"].image.layer,"behind");assert.equal(design.regions["chat.header"].image.clip,false);});
test("v67 version markers advance and game remains v49",()=>{assert.match(read("frontend-p4b/assets/js/common.js"),/v76-p4b/u);assert.match(read("frontend-p4b/sw.js"),/xinban-shell-v76-p4b/u);assert.match(read("frontend-p4b/sw.js"),/BUILD_REVISION = "v76"/u);assert.match(read("frontend-p4b/assets/js/common.js"),/p4b-sw-controller-refresh-v76/u);assert.match(read("ai-companion-frontend/game/index.html"),/game-v49-p4b/u);});
