"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8");
const Voice=require("../frontend-p4b/assets/js/voice-adapter.js"),VoiceUI=require("../frontend-p4b/assets/js/voice-ui.js");

class MemoryStorage{constructor(value){this.value=value||null;this.writes=[];}getItem(key){return key===Voice.SETTINGS_KEY?this.value:null;}setItem(key,value){this.value=value;this.writes.push([key,value]);}}
class FakeAdapter{constructor(caps={tts:true,stt:true}){this.caps=caps;this.spoken=[];this.stops=0;this.options=null;}capabilities(){return this.caps;}speak(text,options){this.spoken.push(text);this.speakOptions=options;return this.caps.tts;}pause(){this.paused=true;}resume(){this.resumed=true;}stop(){this.stops+=1;}abortRecognition(){this.aborted=true;}startRecognition(options){this.options=options;return this.caps.stt;}stopRecognition(){this.recognitionStopped=true;}}
const createNode=()=>({value:"",disabled:false,hidden:true,dataset:{},title:"",listeners:{},setAttribute(key,value){this[key]=value;},addEventListener(type,fn){this.listeners[type]=fn;},dispatchEvent(){this.dispatched=true;},focus(){this.focused=true;}});
const createController=(adapter=new FakeAdapter(),storage=new MemoryStorage())=>{const input=createNode(),mic=createNode(),status=createNode(),windowRef={Event:class{},setTimeout:fn=>fn()},documentRef={documentElement:{toggleAttribute(){}},querySelectorAll(){return[];}};return{input,mic,status,controller:new VoiceUI.VoiceUIController({windowRef,documentRef,adapter,storage,input,micButton:mic,statusNode:status})};};

test("v77 voice settings defaults and strict sanitize",()=>{assert.deepEqual(new Voice.VoiceSettingsStore(new MemoryStorage()).load(),Voice.DEFAULT_SETTINGS);assert.deepEqual(Voice.sanitizeSettings({autoRead:1,rate:99,pitch:-3,volume:"bad",recognitionLanguage:"xx",showInterimTranscript:false,transcript:"secret"}),{version:1,autoRead:false,voiceURI:"",voiceName:"",voiceLang:"",rate:1.6,pitch:.7,volume:1,recognitionLanguage:"zh-CN",showInterimTranscript:false});});
test("v77 settings persist only stable voice identity and bounded scalar fields",()=>{const storage=new MemoryStorage(),store=new Voice.VoiceSettingsStore(storage),saved=store.save({autoRead:true,voiceURI:"uri",voiceName:"name",voiceLang:"zh-CN",rate:.1,pitch:9,volume:-2,recognitionLanguage:"ja-JP",showInterimTranscript:true,audio:"blob",transcriptHistory:["x"]});assert.equal(saved.rate,.6);assert.equal(saved.pitch,1.3);assert.equal(saved.volume,0);assert.deepEqual(Object.keys(JSON.parse(storage.value)).sort(),Object.keys(Voice.DEFAULT_SETTINGS).sort());assert.doesNotMatch(storage.value,/blob|transcriptHistory/u);});
test("v77 normalizes markdown, code blocks and bare URLs without changing source",()=>{const source="# 你好 **沉**\n```js\nsecret()\n```\n![月亮](https://img.invalid/a.png) [回家](https://example.com) https://evil.invalid/x";assert.equal(Voice.normalizeSpeechText(source),"你好 沉 月亮 回家");assert.match(source,/secret/u);});
test("v77 chunks long speech by sentence and keeps chunks bounded",()=>{const chunks=Voice.chunkSpeechText(`${"你好。".repeat(100)}结束`,220);assert.ok(chunks.length>1);assert.ok(chunks.every(chunk=>chunk.length<=220));assert.equal(chunks.join(""),`${"你好。".repeat(100)}结束`);});
test("BrowserVoiceAdapter unsupported fallback and stop clear the whole queue",()=>{const unsupported=new Voice.BrowserVoiceAdapter({});assert.deepEqual(unsupported.capabilities(),{tts:false,stt:false});assert.equal(unsupported.speak("你好"),false);const utterances=[],synthesis={speaking:false,speak(item){utterances.push(item);},cancel(){this.cancelled=true;},pause(){},resume(){},getVoices(){return[];}},windowRef={speechSynthesis:synthesis,SpeechSynthesisUtterance:class{}};const adapter=new Voice.BrowserVoiceAdapter(windowRef);adapter.speak("第一句。第二句。",{maxChunkLength:4});assert.ok(adapter.queue.length);adapter.stop();assert.deepEqual(adapter.queue,[]);assert.equal(synthesis.cancelled,true);});
test("BrowserVoiceAdapter pause and resume preserve the active utterance and chunk queue",()=>{const calls={speak:0,pause:0,resume:0,cancel:0},utterances=[],synthesis={speaking:true,paused:false,speak(item){calls.speak+=1;utterances.push(item);},pause(){calls.pause+=1;this.paused=true;},resume(){calls.resume+=1;this.paused=false;},cancel(){calls.cancel+=1;},getVoices(){return[];}},windowRef={speechSynthesis:synthesis,SpeechSynthesisUtterance:class{}};const adapter=new Voice.BrowserVoiceAdapter(windowRef);assert.equal(adapter.speak("第一句。第二句。第三句。",{maxChunkLength:4}),true);const initialCancel=calls.cancel,queued=adapter.queue.length,active=adapter.activeUtterance;assert.equal(calls.speak,1);assert.equal(adapter.playbackState,"playing");assert.equal(adapter.pause(),true);assert.equal(calls.pause,1);assert.equal(calls.cancel,initialCancel);assert.equal(calls.speak,1);assert.equal(adapter.queue.length,queued);assert.equal(adapter.playbackState,"paused");active.onend();assert.equal(calls.speak,1);assert.equal(adapter.queue.length,queued);assert.equal(adapter.activeUtterance,active);assert.equal(adapter.resume(),true);assert.equal(calls.resume,1);assert.equal(calls.speak,1);assert.equal(adapter.activeUtterance,active);assert.equal(adapter.playbackState,"playing");adapter.pause();adapter.stop();assert.equal(calls.cancel,initialCancel+1);assert.deepEqual(adapter.queue,[]);assert.equal(adapter.activeUtterance,null);assert.equal(adapter.playbackState,"idle");});
test("v77 switching TTS messages cancels the old playback before speaking the new one",()=>{const order=[],synthesis={speak(){order.push("speak");},pause(){order.push("pause");},resume(){order.push("resume");},cancel(){order.push("cancel");},getVoices(){return[];}},windowRef={speechSynthesis:synthesis,SpeechSynthesisUtterance:class{}},adapter=new Voice.BrowserVoiceAdapter(windowRef),storage=new MemoryStorage(),input=createNode(),mic=createNode(),status=createNode(),documentRef={documentElement:{toggleAttribute(){}},querySelectorAll(){return[];}},controller=new VoiceUI.VoiceUIController({windowRef:{Event:class{},setTimeout:fn=>fn()},documentRef,adapter,storage,input,micButton:mic,statusNode:status});controller.speakMessage({id:"a",role:"assistant",content:"第一条"});const boundary=order.length;controller.speakMessage({id:"b",role:"assistant",content:"第二条"});assert.deepEqual(order.slice(boundary),["cancel","speak"]);assert.equal(controller.activeMessageId,"b");});
test("v77 allows only assistant final messages and one active speaker",()=>{const adapter=new FakeAdapter(),{controller}=createController(adapter);assert.equal(controller.speakMessage({id:"u",role:"user",content:"no"}),false);assert.equal(controller.speakMessage({id:"a",role:"assistant",content:"one"}),true);assert.equal(controller.speakMessage({id:"b",role:"assistant",content:"two"}),true);assert.deepEqual(adapter.spoken,["one","two"]);assert.equal(controller.activeMessageId,"b");assert.ok(adapter.stops>=2);});
test("v77 autoRead defaults off, excludes history/streaming and completes once",()=>{const adapter=new FakeAdapter(),{controller}=createController(adapter);const message={id:"a",role:"assistant",content:"完成"};assert.equal(controller.onAssistantMessageCompleted(message),false);assert.deepEqual(adapter.spoken,[]);controller.store.save({...Voice.DEFAULT_SETTINGS,autoRead:true});assert.equal(controller.onAssistantMessageCompleted({...message,id:"history"},{history:true}),false);assert.equal(controller.onAssistantMessageCompleted({...message,id:"partial"},{streaming:true}),false);const fresh={...message,id:"fresh"};assert.equal(controller.onAssistantMessageCompleted(fresh),true);assert.equal(controller.onAssistantMessageCompleted(fresh),false);assert.deepEqual(adapter.spoken,["完成"]);});
test("v77 STT final safely merges composer, interim stays status, and never sends",()=>{const adapter=new FakeAdapter(),{controller,input,mic,status}=createController(adapter);input.value="已有文字";mic.listeners.click();adapter.options.onInterim("临时文本");assert.equal(input.value,"已有文字");assert.match(status.textContent,/临时文本/u);input.value="已有文字（用户编辑）";adapter.options.onFinal("识别文本");assert.equal(input.value,"已有文字（用户编辑） 识别文本");assert.equal(input.dispatched,true);assert.equal(controller.recognitionState,"result");assert.equal(adapter.options.autoSend,undefined);});
test("v77 microphone denial is isolated and unsupported mic is disabled",()=>{const unsupported=createController(new FakeAdapter({tts:true,stt:false}));assert.equal(unsupported.mic.disabled,true);const supported=createController();supported.mic.listeners.click();assert.doesNotThrow(()=>supported.controller.adapter.options.onError("not-allowed"));assert.equal(supported.status.textContent,"未获得麦克风权限");});
test("v77 integration uses existing send flow and has no audio persistence or Gateway upload",()=>{const chat=read("frontend-p4b/assets/js/chat.js"),adapter=read("frontend-p4b/assets/js/voice-adapter.js"),ui=read("frontend-p4b/assets/js/voice-ui.js");assert.match(chat,/handleSend/u);assert.match(chat,/onAssistantMessageCompleted\(reply/u);assert.doesNotMatch(`${chat}\n${adapter}\n${ui}`,/fetch\(|FormData|AudioBlob|MediaRecorder|\/api\/.*(?:voice|audio)/u);assert.doesNotMatch(`${adapter}\n${ui}`,/sendMessage|messages\.push|saveConversationHistory/u);});
test("v77 assistant-only controls, settings UI, protected layout and build markers",()=>{const chat=read("frontend-p4b/assets/js/chat.js"),html=read("frontend-p4b/chat.html"),settings=read("frontend-p4b/settings.html"),css=read("frontend-p4b/assets/css/voice-v77.css"),sw=read("frontend-p4b/sw.js"),game=read("ai-companion-frontend/game/index.html");assert.match(chat,/message\.role === "assistant"[\s\S]*\["voice", "朗读"\]/u);assert.match(chat,/!message\.transient/u);assert.doesNotMatch(chat,/role === "user"[\s\S]{0,160}\["voice"/u);for(const marker of ["自动朗读沉的新回复","沉的声音","语速","音调","音量","语音输入语言","显示识别临时文本","语音识别由浏览器提供"])assert.ok(settings.includes(marker),marker);assert.match(html,/voice-adapter\.js\?v=v77-p4b/u);assert.doesNotMatch(css,/\.(?:chat-shell|chat-main|message-list|composer)(?:\s|\{|,)[^{]*\{[^}]*(?:display|position|height|overflow|z-index|transform)\s*:/u);assert.match(sw,/xinban-shell-v77-p4b/u);assert.match(sw,/BUILD_REVISION = "v77"/u);assert.match(sw,/voice-adapter\.js\?v=v77-p4b/u);assert.match(game,/game-v49-p4b/u);});
