"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs");
const {VoiceSessionController:C}=require("../frontend-p4b/assets/js/voice-session.js"),V=require("../frontend-p4b/assets/js/voice-adapter.js");
function fixture(caps={stt:true,tts:true}){
  const tasks=new Map(),calls=[],clock={setTimeout(fn,delay){const id={};tasks.set(id,{fn,delay});return id;},clearTimeout(id){tasks.delete(id);}},adapter={capabilities:()=>caps,stop(){calls.push("stop");},abortRecognition(){calls.push("abort");},startRecognition(o){calls.push("listen");this.r=o;return caps.stt;},speak(text,o){calls.push("speak");this.t=o;o.onStart();return caps.tts;},pause(){calls.push("pause");return true;},resume(){calls.push("resume");return true;}};
  let draft="",busy=false,sends=0,confirmed=false;const doc={visibilityState:"visible"};const c=new C({adapter,clock,documentRef:doc,getDraft:()=>draft,setDraft:x=>draft=x,getBusy:()=>busy,getSessionId:()=>"a",confirmContinuous:()=>confirmed,send:()=>{sends++;draft="";c.thinking();return true;}});
  return{c,adapter,calls,tasks,doc,setBusy:x=>busy=x,setConfirm:x=>confirmed=x,get sends(){return sends;},get draft(){return draft;},tick(){const batch=[...tasks.values()];tasks.clear();batch.forEach(x=>x.fn());},reply(id="a",opts){return c.completedReply({id,role:"assistant",content:"你好"},opts);}};
}
test("v78 defaults idle, inactive, continuous false, session autoSpeak true; open close",()=>{const f=fixture();assert.equal(f.c.state,"idle");assert.equal(f.c.active,false);assert.equal(f.c.continuousConversation,false);assert.equal(f.c.sessionAutoSpeak,true);f.c.open();assert.equal(f.c.active,true);f.c.close();assert.equal(f.c.active,false);});
test("first continuous activation requires confirmation; cancellation and later approval",async()=>{const f=fixture();f.c.open();assert.equal(await f.c.setContinuous(true),false);f.setConfirm(true);assert.equal(await f.c.setContinuous(true),true);await f.c.setContinuous(false);f.setConfirm(false);assert.equal(await f.c.setContinuous(true),true);});
test("normal final writes composer, review sends through supplied existing pipeline only",async()=>{const f=fixture();f.c.open();f.c.listen();f.adapter.r.onFinal("你好");assert.equal(f.c.state,"review");assert.equal(f.draft,"你好");assert.equal(f.sends,0);await f.c.sendReview();assert.equal(f.sends,1);assert.equal(f.c.state,"thinking");});
test("continuous final sends exactly once per turn despite duplicate result/end races, including identical next turn",async()=>{const f=fixture();f.c.open();f.setConfirm(true);await f.c.setContinuous(true);for(let i=0;i<3;i++){assert.equal(f.c.listen(),true);const r=f.adapter.r;r.onFinal("一样");r.onFinal("一样");r.onEnd();assert.equal(f.sends,i+1);f.reply(String(i));f.adapter.t.onEnd();f.tick();if(i<2){assert.equal(f.c.state,"listening");f.c.stop();}}});
for(const state of ["sending","thinking","speaking","paused"]){test(`cannot start recognition during ${state}`,()=>{const f=fixture();f.c.open();f.c.state=state;assert.equal(f.c.listen(),false);assert.equal(f.calls.includes("listen"),false);});}
test("TTS end waits 450ms and requires continuous; stops cancel all resources",async()=>{const f=fixture();f.c.open();f.reply();f.adapter.t.onEnd();assert.equal(f.tasks.size,0);f.setConfirm(true);await f.c.setContinuous(true);f.reply("b");f.adapter.t.onEnd();assert.equal(f.c.state,"idle");assert.equal([...f.tasks.values()][0].delay,450);f.c.stop();assert.equal(f.tasks.size,0);f.tick();assert.equal(f.c.state,"idle");assert.ok(f.calls.includes("stop"));assert.ok(f.calls.includes("abort"));});
test("continuous off cancels pending listen",async()=>{const f=fixture();f.c.open();f.setConfirm(true);await f.c.setContinuous(true);f.reply();f.adapter.t.onEnd();await f.c.setContinuous(false);f.tick();assert.equal(f.c.state,"idle");});
test("interrupt stops TTS before delayed STT, double click cannot create two recognitions",()=>{const f=fixture();f.c.open();f.reply();f.c.interrupt();f.c.interrupt();assert.equal(f.tasks.size,1);assert.equal([...f.tasks.values()][0].delay,275);assert.equal(f.calls.at(-1),"stop");f.tick();assert.equal(f.calls.filter(x=>x==="listen").length,1);});
test("hidden aborts recognition; visible never opens microphone; late final ignored",()=>{const f=fixture();f.c.open();f.c.listen();const r=f.adapter.r;f.doc.visibilityState="hidden";f.c.visibilityChanged();f.doc.visibilityState="visible";f.c.visibilityChanged();r.onFinal("late");f.tick();assert.equal(f.sends,0);assert.equal(f.c.state,"idle");assert.equal(f.calls.filter(x=>x==="listen").length,1);});
test("hidden pauses TTS; explicit resume permits completion without reopening mic",()=>{const f=fixture();f.c.open();f.reply();f.doc.visibilityState="hidden";f.c.visibilityChanged();assert.equal(f.c.state,"paused");f.doc.visibilityState="visible";f.c.visibilityChanged();f.c.resume();assert.equal(f.c.state,"speaking");f.adapter.t.onEnd();assert.equal(f.c.state,"idle");});
test("session switch closes voice and invalidates stale completion",()=>{const f=fixture();f.c.open();const generation=f.c.generation;f.c.sessionChanged("b");assert.equal(f.c.active,false);f.c.open();assert.equal(f.reply("late",{generation}),false);});
test("completion ID dedup excludes history and streaming; opening overlay never replays",()=>{const f=fixture();f.c.open();assert.equal(f.reply("history",{history:true}),false);assert.equal(f.reply("partial",{streaming:true}),false);assert.equal(f.reply(),true);assert.equal(f.reply(),false);f.c.close();f.c.open();assert.equal(f.reply(),false);assert.equal(f.calls.filter(x=>x==="speak").length,1);});
for(const error of ["not-allowed","audio-capture","no-speech","network","aborted"]){test(`${error} stops continuous without retry`,async()=>{const f=fixture();f.c.open();f.setConfirm(true);await f.c.setContinuous(true);f.c.listen();f.adapter.r.onError(error);f.tick();assert.equal(f.c.state,"error");assert.equal(f.tasks.size,0);assert.equal(f.calls.filter(x=>x==="listen").length,1);});}
test("assistant and TTS errors stop continuous",()=>{for(const error of ["assistant","tts"]){const f=fixture();f.c.open();if(error==="assistant")f.c.assistantError();else{f.reply();f.adapter.t.onError();}assert.equal(f.c.state,"error");assert.equal(f.tasks.size,0);}});
test("unsupported STT fallback remains isolated",()=>{const f=fixture({stt:false,tts:true});f.c.open();assert.equal(f.c.listen(),false);assert.match(f.c.notice,/不支持/);});
test("manual composer edit prevents automatic listening",async()=>{const f=fixture();f.c.open();f.setConfirm(true);await f.c.setContinuous(true);f.reply();f.c.composerEdited();f.adapter.t.onEnd();assert.equal(f.tasks.size,0);});
test("Wake Lock missing/rejected capability falls back and late grant is released",async()=>{const f=fixture();f.c.open();await f.c.acquireWakeLock();f.c.navigatorRef={wakeLock:{request:()=>Promise.reject(new Error("denied"))}};await f.c.acquireWakeLock();let release=0,grant;f.c.navigatorRef={wakeLock:{request:()=>new Promise(resolve=>grant=resolve)}};const pending=f.c.acquireWakeLock();f.c.close();grant({release:()=>release++});await pending;assert.equal(release,1);});
test("chunks merge short sentences, count Unicode and bound at 220",()=>{assert.deepEqual(V.chunkSpeechText("嗯。知道了。你先吃饭。"),["嗯。知道了。你先吃饭。"]);const text="😀你好。".repeat(200),chunks=V.chunkSpeechText(text);assert.ok(chunks.every(x=>Array.from(x).length<=220));assert.equal(chunks.join(""),text);});
test("chunk pause/resume and stop cancel timer without restarting playback",()=>{const tasks=new Map(),spoken=[],w={SpeechSynthesisUtterance:class{},speechSynthesis:{speak:u=>spoken.push(u),getVoices:()=>[],pause(){},resume(){},cancel(){}},setTimeout(fn){tasks.set(1,fn);return 1;},clearTimeout:id=>tasks.delete(id)},a=new V.BrowserVoiceAdapter(w);a.speak("你好。".repeat(150));spoken[0].onend();assert.equal(tasks.size,1);a.pause();tasks.get(1)();tasks.clear();assert.equal(spoken.length,1);a.resume();assert.equal(spoken.length,2);spoken[1].onend();a.stop();assert.equal(tasks.size,0);assert.equal(a.queue.length,0);});
test("overlay mobile constraints, privacy, protected layout and current cache markers",()=>{const read=p=>fs.readFileSync(p,"utf8"),js=read("frontend-p4b/assets/js/voice-session.js"),css=read("frontend-p4b/assets/css/voice-session-v78.css"),chat=read("frontend-p4b/assets/js/chat.js"),html=read("frontend-p4b/chat.html"),sw=read("frontend-p4b/sw.js");assert.doesNotMatch(js,/fetch\(|MediaRecorder|AudioBlob|FormData|localStorage|EventStore|sendMessage/);assert.match(chat,/send: handleSend/);assert.match(html,/data-vs-confirm-yes>开启/);assert.match(css,/safe-area-inset-bottom/);assert.match(css,/min-height:44px/);assert.match(css,/bottom:var\(--voice-session-nav-gap\)/);assert.match(css,/height:calc\(100dvh - var\(--voice-session-nav-gap\)\)/);assert.doesNotMatch(css,/\.(chat-shell|chat-main|message-list|composer)[\s{]/);assert.match(sw,/xinban-shell-v78-p4b/);assert.match(sw,/BUILD_REVISION = "v78"/);assert.match(sw,/voice-session.js\?v=v78-p4b/);assert.ok(sw.includes("voice-session-v78.css?v=v78-p4b-ui1"));assert.ok(html.includes("voice-session-v78.css?v=v78-p4b-ui1"));assert.match(read("ai-companion-frontend/game/index.html"),/game-v49-p4b/);});
test("v78 voice entry is a separate visible header control from v77 quick mic",()=>{const html=fs.readFileSync("frontend-p4b/chat.html","utf8"),css=fs.readFileSync("frontend-p4b/assets/css/chat.css","utf8");assert.match(html,/data-open-voice-session[^>]*aria-label="语音模式"[^>]*title="语音模式"/);assert.match(html,/data-open-voice-session[\s\S]*?<svg/);assert.match(html,/class="composer__voice"/);assert.match(html,/chat\.css\?v=v78-p4b-entry1/);assert.match(css,/grid-template-columns: 42px minmax\(0, 1fr\) 44px 42px/);assert.match(css,/\.voice-session-entry[\s\S]*width: 44px/);assert.doesNotMatch(css,/\.voice-session-entry[^}]*display:\s*none/);});
test("reopening voice mode always requires explicit continuous activation",async()=>{const f=fixture();f.c.open();f.setConfirm(true);await f.c.setContinuous(true);f.c.close();f.c.open();assert.equal(f.c.continuousConversation,false);});
test("late rejected send cannot put a newly opened session into error",async()=>{const f=fixture();let reject;f.c.send=()=>new Promise((resolve,r)=>{reject=r;});f.c.open();f.c.listen();f.adapter.r.onFinal("text");const pending=f.c.sendReview();f.c.close();f.c.open();reject(new Error("fake failure"));await pending;assert.equal(f.c.state,"idle");});
test("hidden before utterance start cancels pending speech and ignores late start",()=>{const f=fixture();f.adapter.speak=(text,o)=>{f.adapter.t=o;return true;};f.c.open();f.c.thinking();f.reply();f.doc.visibilityState="hidden";f.c.visibilityChanged();const stops=f.calls.filter(x=>x==="stop").length;f.doc.visibilityState="visible";f.c.visibilityChanged();f.adapter.t.onStart();assert.notEqual(f.c.state,"speaking");assert.ok(stops>0);});
test("aborted browser recognition unbinds stale callbacks",()=>{let recognition;const a=new V.BrowserVoiceAdapter({SpeechRecognition:class{constructor(){recognition=this;}start(){}abort(){this.onresult?.({results:[]});}}});a.startRecognition({onFinal:()=>assert.fail("stale final")});a.abortRecognition();assert.equal(recognition.onresult,null);assert.equal(recognition.onend,null);});
test("chunk splitting preserves paragraph boundaries without changing v77 normalization",()=>{const text="甲".repeat(100)+"\n"+"乙".repeat(100);const chunks=V.chunkSpeechText(text);assert.equal(chunks.length,2);assert.equal(chunks[0],"甲".repeat(100));assert.equal(V.normalizeSpeechText("甲\n乙"),"甲 乙");});
for(const reason of ['reject','403','429','503','network','aborted','stream'])test(`assistant ${reason} isolates continuous and permits explicit new turn`,async()=>{const f=fixture();f.c.open();f.setConfirm(true);await f.c.setContinuous(true);f.c.listen();f.adapter.r.onFinal('test');assert.equal(f.c.state,'thinking');f.c.assistantError();assert.equal(f.tasks.size,0);f.tick();assert.equal(f.c.state,'error');assert.equal(f.sends,1);assert.equal(f.calls.filter(x=>x==='listen').length,1);assert.equal(f.reply('late'),false);assert.equal(f.c.listen(),true);f.adapter.r.onFinal('new');assert.equal(f.sends,2);});
test('send rejection reaches error',async()=>{const f=fixture();f.c.open();f.c.listen();f.adapter.r.onFinal('test');f.c.send=async()=>{f.c.thinking();throw Error('fake');};await f.c.sendReview();assert.equal(f.c.state,'error');assert.equal(f.tasks.size,0);});
test('60 second watchdog ends thinking without resend or recognition restart',async()=>{const f=fixture();f.c.open();f.setConfirm(true);await f.c.setContinuous(true);f.c.listen();f.adapter.r.onFinal('test');assert.equal([...f.tasks.values()][0].delay,60000);f.tick();assert.equal(f.c.state,'error');assert.equal(f.c.notice,'等待回复超时，请重试。');f.tick();assert.equal(f.sends,1);assert.equal(f.calls.filter(x=>x==='listen').length,1);assert.equal(f.reply('late'),false);});
for(const action of ['success','failure','exit','switch','hidden','stop'])test(`watchdog cancelled on ${action}`,()=>{const f=fixture();f.c.open();f.c.thinking();assert.equal(f.tasks.size,1);if(action==='success')f.reply();if(action==='failure')f.c.assistantError();if(action==='exit')f.c.close();if(action==='switch')f.c.sessionChanged('b');if(action==='stop')f.c.stop();if(action==='hidden'){f.doc.visibilityState='hidden';f.c.visibilityChanged();}assert.equal(f.tasks.size,0);assert.equal(f.c.watchdog,null);f.tick();assert.notEqual(f.c.state,'thinking');});
const {JSDOM}=require('jsdom');
test('avatar reads resolved header each open, uses configured fallback and never mutates header',()=>{const dom=new JSDOM('<div class="chat-avatar" style="background-image:url(/first.png)">沉</div><div id="overlay"></div>',{url:'https://example.test/chat.html'}),w=dom.window,d=w.document,node=d.querySelector('#overlay'),header=d.querySelector('.chat-avatar');const {syncAvatar}=require('../frontend-p4b/assets/js/voice-session.js');w.CompanionChatAvatars={getImage:()=>'/configured.png'};const before=header.outerHTML;syncAvatar(w,d,node);assert.equal(node.firstChild.src,'https://example.test/first.png');assert.equal(header.outerHTML,before);header.style.backgroundImage='url(/second.png)';syncAvatar(w,d,node);assert.equal(node.firstChild.src,'https://example.test/second.png');node.firstChild.onerror();assert.equal(node.firstChild.src,'https://example.test/configured.png');node.firstChild.onerror();assert.equal(node.querySelector('img'),null);assert.equal(node.textContent,'沉');header.style.backgroundImage='none';w.CompanionChatAvatars.getImage=()=>null;syncAvatar(w,d,node);assert.equal(node.textContent,'沉');dom.window.close();});
test('aborted partial streams notify shared Chat failure without changing ordinary API abort behavior',async()=>{const src=fs.readFileSync('frontend-p4b/assets/js/api.js','utf8');assert.match(src,/options.onStreamFailure\?\.\(\)/);const chat=fs.readFileSync('frontend-p4b/assets/js/chat.js','utf8');assert.match(chat,/onStreamFailure: \(\) => \{ streamFailed = true; \}/);assert.match(chat,/if \(streamFailed \|\| !completeReply\)/);assert.match(chat,/catch \(error\) \{\s*pendingRow.remove\(\);\s*if .*assistantError\(\)/);});

for(const failure of [{status:403},{status:429},{status:503},{code:'NETWORK_ERROR'},{code:'ABORTED'},{code:'INVALID_RESPONSE'}])test(`shared API failure lifecycle ${JSON.stringify(failure)}`,async()=>{
 const vm=require('node:vm'),f=fixture();let calls=0;const window={AppData:{MODEL_CONFIG:{}},MessageProtocol:{toOpenAIMessages:x=>x,createUserMessage:content=>({role:'user',content})},AppProvider:{async *stream(){calls++;yield 'partial';throw Object.assign(Error('fake'),failure);}}};
 vm.runInNewContext(fs.readFileSync('frontend-p4b/assets/js/api.js','utf8'),{window,AbortController});f.c.open();f.c.thinking();let notifications=0;
 try{for await(const chunk of window.AppAPI.sendStreamMessage('fixture',{onStreamFailure(){notifications++;f.c.assistantError();}}))assert.equal(chunk,'partial');}catch(error){assert.notEqual(failure.code,'ABORTED');}
 assert.equal(notifications,1);assert.equal(f.c.state,'error');assert.equal(f.tasks.size,0);assert.equal(window.AppAPI.loading,false);assert.equal(calls,1);
});

const Background=require('../frontend-p4b/assets/js/voice-background.js');
test('voice backgrounds migrate defaults and retain all existing voice preferences',()=>{const original={voiceURI:'uri',voiceName:'name',voiceLang:'zh-CN',rate:1.2,pitch:1.1,volume:.8,recognitionLanguage:'en-US',showInterimTranscript:false,autoRead:true};const value=V.sanitizeSettings(original);for(const key of Object.keys(original))assert.equal(value[key],original[key]);assert.deepEqual(value.voiceSession,{continuousConversation:false,autoSpeak:true,backgroundMode:'follow-chat',backgroundAssetId:''});const updated=V.sanitizeSettings({...value,voiceSession:{continuousConversation:true,autoSpeak:false,backgroundMode:'custom',backgroundAssetId:'12345678-abcd'}});assert.equal(updated.voiceSession.continuousConversation,true);assert.equal(updated.voiceSession.autoSpeak,false);assert.equal(updated.voiceSession.backgroundAssetId,'12345678-abcd');});
for(const id of ['http://x','https://x','data:image/png;base64,x','blob:x','file:/x','javascript:alert(1)','/api/theme/assets/12345678','/var/x','../12345678'])test(`voice rejects non asset ID ${id.split(':')[0]}`,()=>assert.equal(V.sanitizeSettings({voiceSession:{backgroundMode:'custom',backgroundAssetId:id}}).voiceSession.backgroundAssetId,''));
test('follow-chat reads current rendered layers in order on each open',()=>{let foreground='url("https://example.test/a.png")';const shell={},body={};const doc={querySelector:()=>shell,body};const w={getComputedStyle:(node,pseudo)=>({display:'block',opacity:'1',backgroundImage:pseudo?foreground:'url("https://example.test/theme.png")'})};assert.equal(Background.chatBackground(w,doc),foreground);foreground='url("https://example.test/b.png")';assert.equal(Background.chatBackground(w,doc),foreground);foreground='none';assert.equal(Background.chatBackground(w,doc),'url("https://example.test/theme.png")');});
test('background UI uses safe resolver, falls back on missing/load error, restores and stores only ID',async()=>{
 const html=fs.readFileSync('frontend-p4b/chat.html','utf8');const dom=new JSDOM(html,{url:'https://example.test/chat.html'}),w=dom.window,d=w.document;let images=[],saved=null,reads=[];const data=V.sanitizeSettings({voiceURI:'keep'});const store={load:()=>saved||data,save:value=>{saved=V.sanitizeSettings(value);}};
 w.CompanionVoice=V;w.XinbanThemeGateway={request:async()=>({data:{items:[{id:"12345678-abcd"}]}})};w.XinbanThemes={resolveThemeAssetUrl:path=>{reads.push(path);return 'https://example.test'+path;}};w.Image=class{constructor(){images.push(this);}};w.getComputedStyle=()=>({display:'block',opacity:'1',backgroundImage:'url("https://example.test/chat.png")'});
 const dialog=d.querySelector('[data-voice-session]'),bg=Background.mount({windowRef:w,documentRef:d,dialog,store});await bg.open();assert.equal(saved,null);assert.match(dialog.style.getPropertyValue('--voice-background-image'),/chat.png/);
 store.save({...data,voiceSession:{...data.voiceSession,backgroundMode:'custom',backgroundAssetId:'12345678-abcd'}});await bg.open();assert.deepEqual(reads,['/api/theme/assets/12345678-abcd']);images.at(-1).onload();assert.match(dialog.style.getPropertyValue('--voice-background-image'),/12345678-abcd/);await bg.open();images.at(-1).onerror();assert.match(d.querySelector('[data-vb-notice]').textContent,/临时使用聊天背景/);assert.match(dialog.style.getPropertyValue('--voice-background-image'),/chat.png/);w.XinbanThemeGateway.request=async()=>({data:{items:[]}});const count=images.length;await bg.open();assert.equal(images.length,count);assert.match(d.querySelector('[data-vb-notice]').textContent,/不可用/);d.querySelector('[data-vb-restore]').click();assert.equal(saved.voiceSession.backgroundMode,'follow-chat');assert.equal(saved.voiceSession.backgroundAssetId,'');assert.equal(saved.voiceURI,'keep');assert.doesNotMatch(JSON.stringify(saved),/https|chat.png/);
 store.save({...saved,voiceSession:{backgroundMode:'custom',backgroundAssetId:''}});await bg.open();assert.match(d.querySelector('[data-vb-notice]').textContent,/不可用/);const last=images.at(-1);bg.close();last.onload();assert.match(dialog.style.getPropertyValue('--voice-background-image'),/chat.png/);dom.window.close();
});
test('Voice reuses Workshop picker callback before theme mutation, retains cover and nav layout',()=>{const picker=fs.readFileSync('frontend-p4b/assets/js/theme-workshop.js','utf8'),js=fs.readFileSync('frontend-p4b/assets/js/voice-background.js','utf8'),css=fs.readFileSync('frontend-p4b/assets/css/voice-session-v78.css','utf8');assert.match(picker,/openAssetPicker:select/);assert.ok(picker.indexOf('select(raw.id);return;')<picker.indexOf('const asset=rememberAsset(raw)'));assert.match(js,/bridge.openAssetPicker/);assert.doesNotMatch(js,/localStorage|type=.file|FormData|upload/);assert.match(css,/background-size:cover/);assert.match(css,/background-position:center/);assert.match(css,/var\(--theme-bg, #f5f5f5\)/);});

test('immersive header icons retain names without large text buttons',()=>{const dom=new JSDOM(fs.readFileSync('frontend-p4b/chat.html','utf8')),d=dom.window.document;for(const [selector,label] of [['[data-vb-toggle]','语音背景'],['[data-vs-action="close"]','退出语音模式']]){const b=d.querySelector(selector);assert.equal(b.textContent.trim(),'');assert.equal(b.getAttribute('aria-label'),label);assert.equal(b.title,label);assert.ok(b.querySelector('svg'));}dom.window.close();});
for(const [state,actions] of Object.entries({idle:['listen'],listening:['stop'],recognizing:[],review:['send','retry'],sending:[],thinking:[],speaking:['pause','interrupt'],paused:['stop','resume'],error:['listen']}))test(`presentation ${state} exposes only executable actions`,()=>{const dom=new JSDOM(fs.readFileSync('frontend-p4b/chat.html','utf8')),d=dom.window.document,dialog=d.querySelector('[data-voice-session]');require('../frontend-p4b/assets/js/voice-session.js').renderPresentation(dialog,{state,notice:'沉的回复失败'});assert.deepEqual([...dialog.querySelectorAll('[data-vs-action]')].filter(b=>!b.hidden&&b.dataset.vsAction!=='close').map(b=>b.dataset.vsAction).sort(),actions.sort());assert.equal(d.querySelector('[data-vs-exit]').hidden,state!=='error');assert.equal(d.querySelector('[data-vs-review]').hidden,state!=='review');assert.equal(d.querySelector('[data-vs-listening]').hidden,state!=='listening');dom.window.close();});
test('styled switch keeps native keyboard semantics and privacy remains expandable',()=>{const dom=new JSDOM(fs.readFileSync('frontend-p4b/chat.html','utf8')),d=dom.window.document,input=d.querySelector('[data-vs-continuous]');assert.equal(input.type,'checkbox');assert.equal(input.getAttribute('role'),'switch');assert.equal(input.checked,false);assert.ok(input.closest('label'));assert.ok(input.nextElementSibling.classList.contains('voice-switch'));assert.equal(d.querySelector('.voice-privacy').open,false);assert.match(d.querySelector('.voice-privacy').textContent,/在线识别服务/);assert.ok(d.querySelector('[data-vs-confirm-yes]'));dom.window.close();const css=fs.readFileSync('frontend-p4b/assets/css/voice-session-v78.css','utf8');assert.match(css,/prefers-reduced-motion/);assert.match(css,/--voice-control-size:80px/);assert.match(css,/--voice-small-control-size:48px/);assert.match(css,/focus-visible/);assert.doesNotMatch(css,/#[a-f0-9]{6}.*purple|waveform/);});
